# Lista FIXA de ativos para a busca (Dia 25)
# Gerada em 2026-07-15 22:40 a partir do Investidor10 (4 paginas cada).
# Nao e atualizada em runtime — rode o script de geracao se quiser renovar.

FIIS = [
    {"ticker": "AAZQ11", "nome": "Az Quest Fiagro", "tipo": "fii"},
    {"ticker": "ADSH11", "nome": "Ad Shopping Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "AERO11", "nome": "Hco Opps Aero I", "tipo": "fii"},
    {"ticker": "AFHF11", "nome": "Af Invest Real Estate Multiestratégia Fii", "tipo": "fii"},
    {"ticker": "AFHI11", "nome": "Af Invest Cri", "tipo": "fii"},
    {"ticker": "AGRX11", "nome": "Exes Araguaia", "tipo": "fii"},
    {"ticker": "AIEC11", "nome": "Autonomy Edifícios Corporativos", "tipo": "fii"},
    {"ticker": "AJFI11", "nome": "Aj Malls", "tipo": "fii"},
    {"ticker": "ALZC11", "nome": "Fii Alianzac", "tipo": "fii"},
    {"ticker": "ALZM11", "nome": "Alianza Multiestratégia", "tipo": "fii"},
    {"ticker": "ALZR11", "nome": "Alianza Trust Renda Imobiliária", "tipo": "fii"},
    {"ticker": "ARRI11", "nome": "Átrio Reit Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "ASRF11", "nome": "Asa Retrofits I Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "AZIN11", "nome": "Az Quest Infra-Yield Ii Fip-Ie", "tipo": "fii"},
    {"ticker": "AZPL11", "nome": "Az Quest Panorama Logística Fii", "tipo": "fii"},
    {"ticker": "BBFO11", "nome": "Bb Fundo De Fundos", "tipo": "fii"},
    {"ticker": "BBGO11", "nome": "Bb Fundo De Invest De Crédito Fiagro", "tipo": "fii"},
    {"ticker": "BBIG11", "nome": "Fii Bbig", "tipo": "fii"},
    {"ticker": "BCIA11", "nome": "Bradesco Carteira Imobiliária Ativa", "tipo": "fii"},
    {"ticker": "BCRI11", "nome": "Banestes Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "BDIF11", "nome": "Fundo Em Infraestrutura Btg Pactual Dívida Infra", "tipo": "fii"},
    {"ticker": "BDIV11", "nome": "Btg Pactual Infraestrutura Dividendos", "tipo": "fii"},
    {"ticker": "BICE11", "nome": "Brio Crédito Estruturado", "tipo": "fii"},
    {"ticker": "BIDB11", "nome": "Inter Fi-Infra", "tipo": "fii"},
    {"ticker": "BINC11", "nome": "Bradesco Fic Rf Infra Cdi Créd Priv", "tipo": "fii"},
    {"ticker": "BIPD11", "nome": "Brio Real Estate Iv Fii", "tipo": "fii"},
    {"ticker": "BISE11", "nome": "Infra Bise", "tipo": "fii"},
    {"ticker": "BLMG11", "nome": "Bluemacaw Logística", "tipo": "fii"},
    {"ticker": "BMLT11", "nome": "Permuta Financeira Lote5", "tipo": "fii"},
    {"ticker": "BODB11", "nome": "Bocaina Infra", "tipo": "fii"},
    {"ticker": "BODI11", "nome": "Bocaina Infra Cdi Fic Fi Infra Rf", "tipo": "fii"},
    {"ticker": "BPFF11", "nome": "Brasil Plural Absoluto", "tipo": "fii"},
    {"ticker": "BPML11", "nome": "Btg Pactual Shoppings", "tipo": "fii"},
    {"ticker": "BRCO11", "nome": "Bresco Logística", "tipo": "fii"},
    {"ticker": "BRCR11", "nome": "Btg Pactual Corporate Office", "tipo": "fii"},
    {"ticker": "BRIX11", "nome": "Brix", "tipo": "fii"},
    {"ticker": "BROF11", "nome": "Brpr Corporate Offices", "tipo": "fii"},
    {"ticker": "BRZP11", "nome": "Brz Infra Portos Fdo, Inv. Em Part. Infraestrutura", "tipo": "fii"},
    {"ticker": "BSLT11", "nome": "Permuta Financeira Lote5", "tipo": "fii"},
    {"ticker": "BTAL11", "nome": "Btg Pactual Agro Logística", "tipo": "fii"},
    {"ticker": "BTCI11", "nome": "Fii Btg Pactual Fundo De Cri", "tipo": "fii"},
    {"ticker": "BTHF11", "nome": "Btg Pactual Real Estate Hedge Fund", "tipo": "fii"},
    {"ticker": "BTLG11", "nome": "Btg Pactual Logística", "tipo": "fii"},
    {"ticker": "BTML11", "nome": "Barra Malls Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "BTRA11", "nome": "Btg Pactual Terras Agrícolas", "tipo": "fii"},
    {"ticker": "BTWR11", "nome": "Btowers", "tipo": "fii"},
    {"ticker": "CACR11", "nome": "Cartesia Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "CCME11", "nome": "Canuma Capital Multiestratégia", "tipo": "fii"},
    {"ticker": "CCVA11", "nome": "Canuma Capital Renda Varejo", "tipo": "fii"},
    {"ticker": "CDII11", "nome": "Sparta Infra Cdi Fic Fi-Infra", "tipo": "fii"},
    {"ticker": "CLIN11", "nome": "Clave Índices De Preços", "tipo": "fii"},
    {"ticker": "COPN11", "nome": "Copérnico Fip Infra", "tipo": "fii"},
    {"ticker": "CPFF11", "nome": "Capitânia Reit Fof", "tipo": "fii"},
    {"ticker": "CPLG11", "nome": "Capitânia Logística Fii", "tipo": "fii"},
    {"ticker": "CPOF11", "nome": "Capitânia Office Fii - Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CPSH11", "nome": "Shoppings Aaa Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CPTI11", "nome": "Capitânia Infra Fic Fi-Infra Rf Cp", "tipo": "fii"},
    {"ticker": "CPTR11", "nome": "Capitania Agro Strategies", "tipo": "fii"},
    {"ticker": "CPTS11", "nome": "Capitania Securities Ii", "tipo": "fii"},
    {"ticker": "CPUR11", "nome": "Classe Única Do Capitânia Hbc Renda Urbana", "tipo": "fii"},
    {"ticker": "CRAA11", "nome": "Sparta Fiagro Fdo Inv Nas Cad Prod Agro", "tipo": "fii"},
    {"ticker": "CXAG11", "nome": "Caixa Agências", "tipo": "fii"},
    {"ticker": "CXCI11", "nome": "Caixa Carteira Imobiliária", "tipo": "fii"},
    {"ticker": "CXCO11", "nome": "Caixa Imóveis Corporativos", "tipo": "fii"},
    {"ticker": "CYCR11", "nome": "Cyrela Crédito", "tipo": "fii"},
    {"ticker": "DEVA11", "nome": "Devant Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "DIVS11", "nome": "Sparta Infra Inflação Longa Fi-Infra", "tipo": "fii"},
    {"ticker": "DVLP11", "nome": "Speciale Real Estate Development", "tipo": "fii"},
    {"ticker": "DVLT11", "nome": "Fii Dvlt", "tipo": "fii"},
    {"ticker": "EDGE11", "nome": "Edge Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "EGAF11", "nome": "Ecoagro I Fdo Inv Cadeias Prod Agroind", "tipo": "fii"},
    {"ticker": "EMET11", "nome": "Emet Multiestratégia Fii", "tipo": "fii"},
    {"ticker": "ENDD11", "nome": "Endurance Debt", "tipo": "fii"},
    {"ticker": "EQIN11", "nome": "Nch Eqi High Yield Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "ERCR11", "nome": "Estoque Residencial E Comercial Rj", "tipo": "fii"},
    {"ticker": "ERPA11", "nome": "Europa 105", "tipo": "fii"},
    {"ticker": "EXES11", "nome": "Exes", "tipo": "fii"},
    {"ticker": "FATN11", "nome": "Athena I", "tipo": "fii"},
    {"ticker": "FCFL11", "nome": "Campus Faria Lima", "tipo": "fii"},
    {"ticker": "FGAA11", "nome": "Fg Agro Fdo De Invest", "tipo": "fii"},
    {"ticker": "FIGS11", "nome": "General Shopping Fundo De Investimento", "tipo": "fii"},
    {"ticker": "FIIB11", "nome": "Industrial Do Brasil", "tipo": "fii"},
    {"ticker": "FIIP11", "nome": "Rb Capital Renda I", "tipo": "fii"},
    {"ticker": "FIIP11B", "nome": "Rb Capital Renda I (Old)", "tipo": "fii"},
    {"ticker": "FTCE11B", "nome": "Opportunity", "tipo": "fii"},
    {"ticker": "FYTO11", "nome": "Nch Brasil Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "GAME11", "nome": "Guardian Multiestratégia I", "tipo": "fii"},
    {"ticker": "GARE11", "nome": "Guardian Real Estate", "tipo": "fii"},
    {"ticker": "GCRA11", "nome": "Galápagos Recebíveis Do Agronegócio", "tipo": "fii"},
    {"ticker": "GCRI11", "nome": "Galapagos Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "GGRC11", "nome": "Zagros Renda Imobiliária", "tipo": "fii"},
    {"ticker": "GRAV11", "nome": "Gravataí Shopping", "tipo": "fii"},
    {"ticker": "GRUL11", "nome": "Icatu Vanguarda Gru Logístico", "tipo": "fii"},
    {"ticker": "GSFI11", "nome": "General Shop E Outlets Do Brasil", "tipo": "fii"},
    {"ticker": "GTWR11", "nome": "Green Towers", "tipo": "fii"},
    {"ticker": "GZIT11", "nome": "Gazit Malls", "tipo": "fii"},
    {"ticker": "HABT11", "nome": "Habitat Ii", "tipo": "fii"},
    {"ticker": "HBCR11", "nome": "Hbc Renda Urbana", "tipo": "fii"},
    {"ticker": "HCTR11", "nome": "Hectare Ce", "tipo": "fii"},
    {"ticker": "HDOF11", "nome": "Hedge Desenvolvimento Logístico", "tipo": "fii"},
    {"ticker": "HFOF11", "nome": "Hedge Top", "tipo": "fii"},
    {"ticker": "HGBS11", "nome": "Hedge Brasil Shopping", "tipo": "fii"},
    {"ticker": "HGCR11", "nome": "Cghg Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "HGLG11", "nome": "Pátria Log", "tipo": "fii"},
    {"ticker": "HGRE11", "nome": "Patria Escritórios", "tipo": "fii"},
    {"ticker": "HGRU11", "nome": "Pátria Renda Urbana", "tipo": "fii"},
    {"ticker": "HJCT11", "nome": "Fii Hjct", "tipo": "fii"},
    {"ticker": "HOFC11", "nome": "Hedge Office Income", "tipo": "fii"},
    {"ticker": "HREC11", "nome": "Hedge Recebíveis", "tipo": "fii"},
    {"ticker": "HRES11", "nome": "Fii Hire Residencial I", "tipo": "fii"},
    {"ticker": "HSAF11", "nome": "Hsi Ativos Financeiros", "tipo": "fii"},
    {"ticker": "HSLG11", "nome": "Hsi Logística", "tipo": "fii"},
    {"ticker": "HSML11", "nome": "Hsi Malls", "tipo": "fii"},
    {"ticker": "HSRE11", "nome": "Hsi Renda Imobiliária", "tipo": "fii"},
    {"ticker": "HTMX11", "nome": "Fii Hotel Maxinvest", "tipo": "fii"},
    {"ticker": "IAAG11", "nome": "Inter Amerra - Fiagro", "tipo": "fii"},
    {"ticker": "IBBP11", "nome": "Invista Brazilian Business Park Fii", "tipo": "fii"},
    {"ticker": "ICNE11", "nome": "Ícone Fii", "tipo": "fii"},
    {"ticker": "ICRI11", "nome": "Itaú Crédito Imobiliário Ipca", "tipo": "fii"},
    {"ticker": "IFRA11", "nome": "Itau Fdo Inv Cotas Fdo Incent De Inv Infr. Rf Cp", "tipo": "fii"},
    {"ticker": "IFRI11", "nome": "Itaú Fic Fi Invest Finan Infra Cdi Rf Cp", "tipo": "fii"},
    {"ticker": "INDE11", "nome": "Inter Desenvolvimento Fii", "tipo": "fii"},
    {"ticker": "INLG11", "nome": "Inter Logístico Fii", "tipo": "fii"},
    {"ticker": "IRIM11", "nome": "Iridium", "tipo": "fii"},
    {"ticker": "ISEN11", "nome": "Itaú Isento Março 29 Fic Fi De Infraestrutura", "tipo": "fii"},
    {"ticker": "ISNN11", "nome": "Itaú Isento Julho 28 Fic Fiif Infra Rf Resp Lim", "tipo": "fii"},
    {"ticker": "ISNT11", "nome": "Itaú Isento Março 28 Fic Fi-Infra", "tipo": "fii"},
    {"ticker": "ISTT11", "nome": "Itaú Isento Setembro 29 Fic Fi De Infra Rf", "tipo": "fii"},
    {"ticker": "ITIP11", "nome": "Inter Teva Indice De Papel", "tipo": "fii"},
    {"ticker": "ITIT11", "nome": "Inter Teve Indice De Tijolo", "tipo": "fii"},
    {"ticker": "ITRI11", "nome": "Itaú Total Return Fii", "tipo": "fii"},
    {"ticker": "JCCJ11", "nome": "Jhsf Capital Jardins", "tipo": "fii"},
    {"ticker": "JGPX11", "nome": "Jgp Crédito", "tipo": "fii"},
    {"ticker": "JMBI11", "nome": "Jivemaua Bossanova", "tipo": "fii"},
    {"ticker": "JPPA11", "nome": "Jpp Allocation Mogno", "tipo": "fii"},
    {"ticker": "JSAF11", "nome": "Js Ativos Financeiros", "tipo": "fii"},
    {"ticker": "JSCR11", "nome": "Js Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "JSRE11", "nome": "Js Real Estate Multigestão - Fii", "tipo": "fii"},
    {"ticker": "JURO11", "nome": "Sparta Infra Fic Fi-Infra", "tipo": "fii"},
    {"ticker": "KCRE11", "nome": "Kinea Creditas", "tipo": "fii"},
    {"ticker": "KDIF11", "nome": "Kinea Fi - Infra", "tipo": "fii"},
    {"ticker": "KDOL11", "nome": "Kinea Agro Income Usd Fiagro", "tipo": "fii"},
    {"ticker": "KFOF11", "nome": "Kinea Fii", "tipo": "fii"},
    {"ticker": "KISU11", "nome": "Klima Fic Fundo Imobiliário Suno 30", "tipo": "fii"},
    {"ticker": "KIVO11", "nome": "Kilima Volkano Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "KNCA11", "nome": "Kinea Crédito Agro Fiagro", "tipo": "fii"},
    {"ticker": "KNCR11", "nome": "Kinea Rendimentos Imobiliários Fundos", "tipo": "fii"},
    {"ticker": "KNDI11", "nome": "Kinea Estrategia Infra", "tipo": "fii"},
    {"ticker": "KNHF11", "nome": "Kinea Hedge Fund Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "KNHY11", "nome": "Kinea High Yield Cri", "tipo": "fii"},
    {"ticker": "KNIP11", "nome": "Kinea Índice De Preços Fundo", "tipo": "fii"},
    {"ticker": "KNOX11", "nome": "Knox Debt Fdo. Invest. Part. Infraestrutura", "tipo": "fii"},
    {"ticker": "KNRI11", "nome": "Kinea Renda Imobiliária", "tipo": "fii"},
    {"ticker": "KNSC11", "nome": "Kinea Securities", "tipo": "fii"},
    {"ticker": "KNUQ11", "nome": "Kinea Unique Hy Cdi Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "KOPA11", "nome": "Kinea Oportunidades Agro I", "tipo": "fii"},
    {"ticker": "KORE11", "nome": "Kinea Oportunidades Real Estate", "tipo": "fii"},
    {"ticker": "LASC11", "nome": "Legatus Shoppings", "tipo": "fii"},
    {"ticker": "LIFE11", "nome": "Life Capital", "tipo": "fii"},
    {"ticker": "LKDV11", "nome": "Development V1", "tipo": "fii"},
    {"ticker": "LSAG11", "nome": "Leste Fundo Invest Cad Prod Agroind", "tipo": "fii"},
    {"ticker": "LVBI11", "nome": "Vbi Logístico", "tipo": "fii"},
    {"ticker": "MANA11", "nome": "Manatí Capital Hedge Fund", "tipo": "fii"},
    {"ticker": "MCCI11", "nome": "Mauá Capital Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "MCLO11", "nome": "Mauá Capital Logística", "tipo": "fii"},
    {"ticker": "MCRE11", "nome": "Mauá Capital Real Estate", "tipo": "fii"},
    {"ticker": "MFII11", "nome": "Mérito Desenvolvimento Imobiliário", "tipo": "fii"},
    {"ticker": "MMVE11", "nome": "Mmve Oportunidades Imobiliárias", "tipo": "fii"},
    {"ticker": "MXRF11", "nome": "Maxi Renda", "tipo": "fii"},
    {"ticker": "NCHB11", "nome": "Nch Brasil Recebíveis Imobiliários (Old)", "tipo": "fii"},
    {"ticker": "NEWL11", "nome": "Newport Logística", "tipo": "fii"},
    {"ticker": "NEXG11", "nome": "Nex Crédito Fiagro Imobiliário", "tipo": "fii"},
    {"ticker": "NMKS11", "nome": "Nm Ksm Log", "tipo": "fii"},
    {"ticker": "NSLU11", "nome": "Hospital Nossa Senhora De Lourdes", "tipo": "fii"},
    {"ticker": "NUIF11", "nome": "Nu Fi-Infra", "tipo": "fii"},
    {"ticker": "OGIN11", "nome": "Órama Fic Fi-Infra", "tipo": "fii"},
    {"ticker": "OIAG11", "nome": "Ourinvest Innovation", "tipo": "fii"},
    {"ticker": "OUFF11", "nome": "Ourinvest", "tipo": "fii"},
    {"ticker": "OUJP11", "nome": "Ourinvest Jpp", "tipo": "fii"},
    {"ticker": "OXRL11", "nome": "Fii Oxrl", "tipo": "fii"},
    {"ticker": "PCIP11", "nome": "Patria Crédito Imobiliário Índice De Preços Fii", "tipo": "fii"},
    {"ticker": "PFIN11", "nome": "Perfin Apollo Energia Fip Em Infraestrutura", "tipo": "fii"},
    {"ticker": "PICE11", "nome": "Pátria Infraestrutura Energia", "tipo": "fii"},
    {"ticker": "PLAG11", "nome": "Vbi Agro", "tipo": "fii"},
    {"ticker": "PLCR11", "nome": "Plural Recebíveis", "tipo": "fii"},
    {"ticker": "PMIS11", "nome": "Paramis Hedge Fund", "tipo": "fii"},
    {"ticker": "PMLL11", "nome": "Genial Malls", "tipo": "fii"},
    {"ticker": "PNPR11", "nome": "Panorama Properties", "tipo": "fii"},
    {"ticker": "PORD11", "nome": "Polo Recebíveis Imobiliários Ii", "tipo": "fii"},
    {"ticker": "PPEI11", "nome": "Prisma Proton Energia", "tipo": "fii"},
    {"ticker": "PRIF11", "nome": "Pátria Crédito Infra", "tipo": "fii"},
    {"ticker": "PSEC11", "nome": "Vbi Reits Fof", "tipo": "fii"},
    {"ticker": "PVBI11", "nome": "Vbi Prime Properties", "tipo": "fii"},
    {"ticker": "RBED11", "nome": "Rio Bravo Renda Educacional", "tipo": "fii"},
    {"ticker": "RBFM11", "nome": "Rio Bravo Multiestratégia Fii", "tipo": "fii"},
    {"ticker": "RBHG11", "nome": "Rio Bravo Crédito Imobiliário High Grade", "tipo": "fii"},
    {"ticker": "RBHY11", "nome": "Rio Bravo Crédito Imobiliário High Yield", "tipo": "fii"},
    {"ticker": "RBIF11", "nome": "Rio Bravo Esg", "tipo": "fii"},
    {"ticker": "RBIR11", "nome": "Rb Capital Desenvolvimento Residencial Iv", "tipo": "fii"},
    {"ticker": "RBRK11", "nome": "Rbr Prime Offices", "tipo": "fii"},
    {"ticker": "RBRL11", "nome": "Rbr Log", "tipo": "fii"},
    {"ticker": "RBRP11", "nome": "Rbr Properties", "tipo": "fii"},
    {"ticker": "RBRR11", "nome": "Rbr Rendimento High Grade", "tipo": "fii"},
    {"ticker": "RBRX11", "nome": "Patria Plus Mult. Real Estate - Resp. Limitada", "tipo": "fii"},
    {"ticker": "RBRY11", "nome": "Rbr Private Crédito Imobiliário", "tipo": "fii"},
    {"ticker": "RBVA11", "nome": "Rio Bravo Renda Varejo", "tipo": "fii"},
    {"ticker": "RCRB11", "nome": "Rio Bravo Renda Corporativa", "tipo": "fii"},
    {"ticker": "RDIV11", "nome": "Rbr Desenvolvimento Iv", "tipo": "fii"},
    {"ticker": "RECR11", "nome": "Fii Rec Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "RECT11", "nome": "Fii Rec Renda Imobiliária", "tipo": "fii"},
    {"ticker": "RELG11", "nome": "Rec Logística", "tipo": "fii"},
    {"ticker": "RINV11", "nome": "Real Investor", "tipo": "fii"},
    {"ticker": "RPRI11", "nome": "Rbr Premium Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "RURA11", "nome": "Itaú Asset Rural Fiagro", "tipo": "fii"},
    {"ticker": "RVBI11", "nome": "Vbi Reits Fof (Old)", "tipo": "fii"},
    {"ticker": "RZAG11", "nome": "Fdo Inv Cadeias Prod Agro Riza Agro", "tipo": "fii"},
    {"ticker": "RZAK11", "nome": "Riza Akin", "tipo": "fii"},
    {"ticker": "RZAT11", "nome": "Riza Arctium Real Estate", "tipo": "fii"},
    {"ticker": "RZLC11", "nome": "Riza Lecci", "tipo": "fii"},
    {"ticker": "RZTR11", "nome": "Riza Terrax", "tipo": "fii"},
    {"ticker": "SAPI11", "nome": "Santander Papéis Imobiliários", "tipo": "fii"},
    {"ticker": "SARE11", "nome": "Santander Renda De Aluguéis", "tipo": "fii"},
    {"ticker": "SMRE11", "nome": "Smart Real Estate", "tipo": "fii"},
    {"ticker": "SNAG11", "nome": "Suno Agro", "tipo": "fii"},
    {"ticker": "SNCI11", "nome": "Suno Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "SNEL11", "nome": "Suno Energias Limpas", "tipo": "fii"},
    {"ticker": "SNFF11", "nome": "Sunofofi - Fii", "tipo": "fii"},
    {"ticker": "SNFZ11", "nome": "Suno Fazendas Fiagro – Imobiliário", "tipo": "fii"},
    {"ticker": "SNME11", "nome": "Suno Multiestratégia", "tipo": "fii"},
    {"ticker": "SPDE11", "nome": "Whg Finvest Sp Realty", "tipo": "fii"},
    {"ticker": "SPGM11", "nome": "Spgm", "tipo": "fii"},
    {"ticker": "SPMO11", "nome": "Fii Supremo", "tipo": "fii"},
    {"ticker": "SPXS11", "nome": "Spx Real Estate Multiestratégia", "tipo": "fii"},
    {"ticker": "SUIN11", "nome": "Sulamérica Infra Cdi Fi Fif Infra Renda Fixa", "tipo": "fii"},
    {"ticker": "TEPP11", "nome": "Tellus Properties", "tipo": "fii"},
    {"ticker": "TGAR11", "nome": "Tg Ativo Real", "tipo": "fii"},
    {"ticker": "TMPS11", "nome": "Itaú Tempus", "tipo": "fii"},
    {"ticker": "TOPP11", "nome": "Rbr Top Offices Fii", "tipo": "fii"},
    {"ticker": "TRBL11", "nome": "Fdo De Invest Imob Tellus Rio Bravo Renda Logistic", "tipo": "fii"},
    {"ticker": "TRXB11", "nome": "Trx Real Estate Ii", "tipo": "fii"},
    {"ticker": "TRXF11", "nome": "Trx Real Estate", "tipo": "fii"},
    {"ticker": "TRXY11", "nome": "Trx Hedge Fund", "tipo": "fii"},
    {"ticker": "TVRI11", "nome": "Tivio Renda Imobiliária Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "URPR11", "nome": "Urca Prime Renda", "tipo": "fii"},
    {"ticker": "VANG11", "nome": "Vang Infra", "tipo": "fii"},
    {"ticker": "VCJR11", "nome": "Vectis Juros Real", "tipo": "fii"},
    {"ticker": "VCRA11", "nome": "Vectis Datagro Cr Agr", "tipo": "fii"},
    {"ticker": "VCRI11", "nome": "Vinci Credit", "tipo": "fii"},
    {"ticker": "VCRR11", "nome": "Vectis Renda Residencial", "tipo": "fii"},
    {"ticker": "VGHF11", "nome": "Valora Hedge", "tipo": "fii"},
    {"ticker": "VGIA11", "nome": "Valora Cra Fdo Inv Nas Cad Prod Agro", "tipo": "fii"},
    {"ticker": "VGII11", "nome": "Fii Vgii", "tipo": "fii"},
    {"ticker": "VGIP11", "nome": "Valora Cri Índice De Preço", "tipo": "fii"},
    {"ticker": "VGIR11", "nome": "Valora Re Iii", "tipo": "fii"},
    {"ticker": "VGRI11", "nome": "Valora Renda Imob Fundo De Inves Imob", "tipo": "fii"},
    {"ticker": "VHFA11", "nome": "Valora Hedge Fund Agro - Fiagro - Imobiliário", "tipo": "fii"},
    {"ticker": "VIGT11", "nome": "Vinci Energia", "tipo": "fii"},
    {"ticker": "VILG11", "nome": "Vinci Logística", "tipo": "fii"},
    {"ticker": "VINF11", "nome": "Vinland Infraestrutura Fi Fif Debentures Infra", "tipo": "fii"},
    {"ticker": "VINO11", "nome": "Vinci Offices", "tipo": "fii"},
    {"ticker": "VISC11", "nome": "Vinci Shopping Centers", "tipo": "fii"},
    {"ticker": "VIUR11", "nome": "Vinci Imóveis Urbanos", "tipo": "fii"},
    {"ticker": "VPPR11", "nome": "V2 Prime Properties", "tipo": "fii"},
    {"ticker": "VRTA11", "nome": "Fator Verita", "tipo": "fii"},
    {"ticker": "VRTM11", "nome": "Fator Verità Multiestratégia", "tipo": "fii"},
    {"ticker": "VVRI11", "nome": "V2 Renda Imobiliária Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "VXXV11", "nome": "Vx Xvi", "tipo": "fii"},
    {"ticker": "WHGR11", "nome": "Whg Real Estate", "tipo": "fii"},
    {"ticker": "XLPR11", "nome": "Xlpr Fundo De Investimento Imobiliário - Fii", "tipo": "fii"},
    {"ticker": "XPCA11", "nome": "Xp Crédito Agrícola", "tipo": "fii"},
    {"ticker": "XPCI11", "nome": "Xp Credito Imobiliário", "tipo": "fii"},
    {"ticker": "XPIE11", "nome": "Xp Infra Ii Fdo De Inv Part Ie", "tipo": "fii"},
    {"ticker": "XPIN11", "nome": "Invista Industrial", "tipo": "fii"},
    {"ticker": "XPLG11", "nome": "Xp Log", "tipo": "fii"},
    {"ticker": "XPML11", "nome": "Xp Malls Fundos", "tipo": "fii"},
    {"ticker": "XPSF11", "nome": "Xp Selection Fundo De Fundos", "tipo": "fii"},
]

ACOES = [
    {"ticker": "ABCB4", "nome": "Banco Abc Brasil", "tipo": "acao"},
    {"ticker": "ABEV3", "nome": "Ambev", "tipo": "acao"},
    {"ticker": "AFLT3", "nome": "Afluente", "tipo": "acao"},
    {"ticker": "AGRO3", "nome": "Brasilagro", "tipo": "acao"},
    {"ticker": "ALLD3", "nome": "Allied", "tipo": "acao"},
    {"ticker": "ALOS3", "nome": "Allos", "tipo": "acao"},
    {"ticker": "ALPA4", "nome": "Alpargatas", "tipo": "acao"},
    {"ticker": "ALPK3", "nome": "Estapar", "tipo": "acao"},
    {"ticker": "ALUP11", "nome": "Alupar", "tipo": "acao"},
    {"ticker": "ANIM3", "nome": "Anima", "tipo": "acao"},
    {"ticker": "ARML3", "nome": "Armac", "tipo": "acao"},
    {"ticker": "ASAI3", "nome": "Assaí", "tipo": "acao"},
    {"ticker": "AUAU3", "nome": "União Pet", "tipo": "acao"},
    {"ticker": "AXIA3", "nome": "Axia Energia", "tipo": "acao"},
    {"ticker": "AZZA3", "nome": "Azzas 2154", "tipo": "acao"},
    {"ticker": "B3SA3", "nome": "B3", "tipo": "acao"},
    {"ticker": "BAZA3", "nome": "Banco Amazonia", "tipo": "acao"},
    {"ticker": "BBAS3", "nome": "Banco Do Brasil", "tipo": "acao"},
    {"ticker": "BBDC3", "nome": "Banco Bradesco", "tipo": "acao"},
    {"ticker": "BBSE3", "nome": "Bb Seguridade", "tipo": "acao"},
    {"ticker": "BEEF3", "nome": "Minerva", "tipo": "acao"},
    {"ticker": "BEES3", "nome": "Banco Banestes", "tipo": "acao"},
    {"ticker": "BGIP4", "nome": "Banco Banese", "tipo": "acao"},
    {"ticker": "BLAU3", "nome": "Blau Farmacêutica", "tipo": "acao"},
    {"ticker": "BMEB4", "nome": "Banco Mercantil Do Brasil", "tipo": "acao"},
    {"ticker": "BMGB4", "nome": "Banco Bmg", "tipo": "acao"},
    {"ticker": "BMOB3", "nome": "Bemobi Mobile Tech", "tipo": "acao"},
    {"ticker": "BNBR3", "nome": "Banco Nordeste Do Brasil", "tipo": "acao"},
    {"ticker": "BPAC11", "nome": "Banco Btg Pactual", "tipo": "acao"},
    {"ticker": "BRAP4", "nome": "Bradespar", "tipo": "acao"},
    {"ticker": "BRAV3", "nome": "Brava", "tipo": "acao"},
    {"ticker": "BRBI11", "nome": "Br Partners", "tipo": "acao"},
    {"ticker": "BRSR6", "nome": "Banco Banrisul", "tipo": "acao"},
    {"ticker": "BRST3", "nome": "Brisanet", "tipo": "acao"},
    {"ticker": "BSLI3", "nome": "Brb", "tipo": "acao"},
    {"ticker": "CAMB3", "nome": "Cambuci", "tipo": "acao"},
    {"ticker": "CAML3", "nome": "Camil", "tipo": "acao"},
    {"ticker": "CASN3", "nome": "Casan", "tipo": "acao"},
    {"ticker": "CBAV3", "nome": "Cba", "tipo": "acao"},
    {"ticker": "CEAB3", "nome": "Cea Modas", "tipo": "acao"},
    {"ticker": "CEBR3", "nome": "Ceb", "tipo": "acao"},
    {"ticker": "CEEB3", "nome": "Coelba", "tipo": "acao"},
    {"ticker": "CEGR3", "nome": "Ceg", "tipo": "acao"},
    {"ticker": "CGAS3", "nome": "Comgás", "tipo": "acao"},
    {"ticker": "CGRA4", "nome": "Grazziotin", "tipo": "acao"},
    {"ticker": "CLSC4", "nome": "Celesc", "tipo": "acao"},
    {"ticker": "CMIG4", "nome": "Cemig", "tipo": "acao"},
    {"ticker": "CMIN3", "nome": "Csn Mineração", "tipo": "acao"},
    {"ticker": "COCE5", "nome": "Coelce", "tipo": "acao"},
    {"ticker": "COGN3", "nome": "Cogna Educação", "tipo": "acao"},
    {"ticker": "CPFE3", "nome": "Cpfl Energia", "tipo": "acao"},
    {"ticker": "CPLE3", "nome": "Copel", "tipo": "acao"},
    {"ticker": "CSED3", "nome": "Cruzeiro Do Sul Educacional", "tipo": "acao"},
    {"ticker": "CSMG3", "nome": "Copasa", "tipo": "acao"},
    {"ticker": "CSUD3", "nome": "Csu Digital", "tipo": "acao"},
    {"ticker": "CURY3", "nome": "Cury", "tipo": "acao"},
    {"ticker": "CXSE3", "nome": "Caixa Seguridade", "tipo": "acao"},
    {"ticker": "CYRE3", "nome": "Cyrela", "tipo": "acao"},
    {"ticker": "DESK3", "nome": "Desktop", "tipo": "acao"},
    {"ticker": "DEXP3", "nome": "Dexxos Participações", "tipo": "acao"},
    {"ticker": "DIRR3", "nome": "Direcional Engenharia", "tipo": "acao"},
    {"ticker": "DOHL4", "nome": "Dohler", "tipo": "acao"},
    {"ticker": "ECOR3", "nome": "Ecorodovias", "tipo": "acao"},
    {"ticker": "EGIE3", "nome": "Engie Brasil", "tipo": "acao"},
    {"ticker": "EKTR3", "nome": "Elektro", "tipo": "acao"},
    {"ticker": "EMBJ3", "nome": "Embraer", "tipo": "acao"},
    {"ticker": "ENGI11", "nome": "Energisa", "tipo": "acao"},
    {"ticker": "ENMT4", "nome": "Energisa Mato Grosso", "tipo": "acao"},
    {"ticker": "EQMA3B", "nome": "Equatorial Maranhao Distribuidora De Energia Sa", "tipo": "acao"},
    {"ticker": "EQPA3", "nome": "Equatorial Para Distribuidora De Energia S.a.", "tipo": "acao"},
    {"ticker": "EQTL3", "nome": "Equatorial Energia", "tipo": "acao"},
    {"ticker": "ESPA3", "nome": "Espaçolaser", "tipo": "acao"},
    {"ticker": "EUCA3", "nome": "Eucatex", "tipo": "acao"},
    {"ticker": "EVEN3", "nome": "Even", "tipo": "acao"},
    {"ticker": "EZTC3", "nome": "Ez Tec", "tipo": "acao"},
    {"ticker": "FESA4", "nome": "Ferbasa", "tipo": "acao"},
    {"ticker": "FIQE3", "nome": "Unifique", "tipo": "acao"},
    {"ticker": "FLRY3", "nome": "Fleury", "tipo": "acao"},
    {"ticker": "FRAS3", "nome": "Fras-Le", "tipo": "acao"},
    {"ticker": "GEPA4", "nome": "Rio Paranapanema", "tipo": "acao"},
    {"ticker": "GGBR3", "nome": "Gerdau", "tipo": "acao"},
    {"ticker": "GGPS3", "nome": "Grupo Gps", "tipo": "acao"},
    {"ticker": "GMAT3", "nome": "Grupo Mateus", "tipo": "acao"},
    {"ticker": "GOAU4", "nome": "Metalúrgica Gerdau", "tipo": "acao"},
    {"ticker": "GPAR3", "nome": "Celgpar", "tipo": "acao"},
    {"ticker": "GRND3", "nome": "Grendene", "tipo": "acao"},
    {"ticker": "HYPE3", "nome": "Hypera", "tipo": "acao"},
    {"ticker": "IGTI3", "nome": "Jereissati", "tipo": "acao"},
    {"ticker": "INTB3", "nome": "Intelbras", "tipo": "acao"},
    {"ticker": "IRBR3", "nome": "Irb", "tipo": "acao"},
    {"ticker": "ISAE4", "nome": "Isa Energia Brasil", "tipo": "acao"},
    {"ticker": "ITSA4", "nome": "Itaúsa", "tipo": "acao"},
    {"ticker": "ITUB4", "nome": "Banco Itaú", "tipo": "acao"},
    {"ticker": "JHSF3", "nome": "Jhsf", "tipo": "acao"},
    {"ticker": "JSLG3", "nome": "Jsl", "tipo": "acao"},
    {"ticker": "KEPL3", "nome": "Kepler Weber", "tipo": "acao"},
    {"ticker": "KLBN11", "nome": "Klabin", "tipo": "acao"},
    {"ticker": "LAVV3", "nome": "Lavvi", "tipo": "acao"},
    {"ticker": "LEVE3", "nome": "Mahle-Metal Leve", "tipo": "acao"},
    {"ticker": "LOGG3", "nome": "Log", "tipo": "acao"},
    {"ticker": "LREN3", "nome": "Lojas Renner", "tipo": "acao"},
    {"ticker": "LWSA3", "nome": "Lwsa - Locaweb", "tipo": "acao"},
    {"ticker": "MATD3", "nome": "Hospital Mater Dei", "tipo": "acao"},
    {"ticker": "MDIA3", "nome": "M. Dias Branco", "tipo": "acao"},
    {"ticker": "MDNE3", "nome": "Moura Dubeux Engenharia S/A", "tipo": "acao"},
    {"ticker": "MELK3", "nome": "Melnick", "tipo": "acao"},
    {"ticker": "MGLU3", "nome": "Magazine Luiza", "tipo": "acao"},
    {"ticker": "MILS3", "nome": "Mills", "tipo": "acao"},
    {"ticker": "MLAS3", "nome": "Multilaser", "tipo": "acao"},
    {"ticker": "MOTV3", "nome": "Motiva Sa", "tipo": "acao"},
    {"ticker": "MOVI3", "nome": "Movida", "tipo": "acao"},
    {"ticker": "MRSA3B", "nome": "Mrs Logística", "tipo": "acao"},
    {"ticker": "MTRE3", "nome": "Mitre Realty", "tipo": "acao"},
    {"ticker": "MTSA4", "nome": "Metisa", "tipo": "acao"},
    {"ticker": "MULT3", "nome": "Multiplan", "tipo": "acao"},
    {"ticker": "MYPK3", "nome": "Iochpe Maxion", "tipo": "acao"},
    {"ticker": "OFSA3", "nome": "Ouro Fino Saúde Animal", "tipo": "acao"},
    {"ticker": "OPCT3", "nome": "Oceanpact", "tipo": "acao"},
    {"ticker": "PASS3", "nome": "Compass", "tipo": "acao"},
    {"ticker": "PATI3", "nome": "Panatlantica", "tipo": "acao"},
    {"ticker": "PEAB3", "nome": "Cia Participações Aliança Da Bahia", "tipo": "acao"},
    {"ticker": "PETR4", "nome": "Petrobras", "tipo": "acao"},
    {"ticker": "PFRM3", "nome": "Profarma", "tipo": "acao"},
    {"ticker": "PGMN3", "nome": "Pague Menos", "tipo": "acao"},
    {"ticker": "PINE4", "nome": "Banco Pine", "tipo": "acao"},
    {"ticker": "PLPL3", "nome": "Plano E Plano", "tipo": "acao"},
    {"ticker": "PNVL3", "nome": "Dimed", "tipo": "acao"},
    {"ticker": "POMO4", "nome": "Marcopolo", "tipo": "acao"},
    {"ticker": "POSI3", "nome": "Positivo", "tipo": "acao"},
    {"ticker": "PSSA3", "nome": "Porto Seguro", "tipo": "acao"},
    {"ticker": "QUAL3", "nome": "Qualicorp", "tipo": "acao"},
    {"ticker": "RADL3", "nome": "Raia Drogasil", "tipo": "acao"},
    {"ticker": "RAIL3", "nome": "Rumo", "tipo": "acao"},
    {"ticker": "RANI3", "nome": "Irani", "tipo": "acao"},
    {"ticker": "RDOR3", "nome": "Rede D'or", "tipo": "acao"},
    {"ticker": "RECV3", "nome": "Petrorecôncavo", "tipo": "acao"},
    {"ticker": "REDE3", "nome": "Rede Energia", "tipo": "acao"},
    {"ticker": "RENT3", "nome": "Localiza", "tipo": "acao"},
    {"ticker": "RIAA3", "nome": "Riachuelo", "tipo": "acao"},
    {"ticker": "ROMI3", "nome": "Romi S.a.", "tipo": "acao"},
    {"ticker": "RPAD3", "nome": "Alfa Holdings", "tipo": "acao"},
    {"ticker": "SANB11", "nome": "Banco Santander", "tipo": "acao"},
    {"ticker": "SAPR11", "nome": "Sanepar", "tipo": "acao"},
    {"ticker": "SAUD3", "nome": "Bradsaúde", "tipo": "acao"},
    {"ticker": "SBFG3", "nome": "Grupo Sbf", "tipo": "acao"},
    {"ticker": "SBSP3", "nome": "Sabesp", "tipo": "acao"},
    {"ticker": "SCAR3", "nome": "São Carlos", "tipo": "acao"},
    {"ticker": "SEER3", "nome": "Ser Educacional", "tipo": "acao"},
    {"ticker": "SHUL4", "nome": "Schulz", "tipo": "acao"},
    {"ticker": "SIMH3", "nome": "Simpar S.a.", "tipo": "acao"},
    {"ticker": "SLCE3", "nome": "Slc Agricola", "tipo": "acao"},
    {"ticker": "SMFT3", "nome": "Smartfit", "tipo": "acao"},
    {"ticker": "SMTO3", "nome": "São Martinho", "tipo": "acao"},
    {"ticker": "SOJA3", "nome": "Boa Safra Sementes", "tipo": "acao"},
    {"ticker": "SUZB3", "nome": "Suzano", "tipo": "acao"},
    {"ticker": "SYNE3", "nome": "Syn", "tipo": "acao"},
    {"ticker": "TAEE11", "nome": "Taesa", "tipo": "acao"},
    {"ticker": "TASA3", "nome": "Taurus Armas", "tipo": "acao"},
    {"ticker": "TECN3", "nome": "Technos", "tipo": "acao"},
    {"ticker": "TEND3", "nome": "Construtora Tenda", "tipo": "acao"},
    {"ticker": "TFCO4", "nome": "Track E Field", "tipo": "acao"},
    {"ticker": "TGMA3", "nome": "Tegma Gestão Logística", "tipo": "acao"},
    {"ticker": "TIMS3", "nome": "Tim", "tipo": "acao"},
    {"ticker": "TOTS3", "nome": "Totvs", "tipo": "acao"},
    {"ticker": "TPIS3", "nome": "Tpi - Triunfo Particip. E Invest. S.a", "tipo": "acao"},
    {"ticker": "TRIS3", "nome": "Trisul", "tipo": "acao"},
    {"ticker": "TTEN3", "nome": "3Tentos", "tipo": "acao"},
    {"ticker": "UGPA3", "nome": "Ultrapar", "tipo": "acao"},
    {"ticker": "UNIP6", "nome": "Unipar Carbocloro", "tipo": "acao"},
    {"ticker": "VALE3", "nome": "Vale", "tipo": "acao"},
    {"ticker": "VAMO3", "nome": "Vamos", "tipo": "acao"},
    {"ticker": "VBBR3", "nome": "Vibra Energia S.a.", "tipo": "acao"},
    {"ticker": "VITT3", "nome": "Vittia", "tipo": "acao"},
    {"ticker": "VIVA3", "nome": "Vivara", "tipo": "acao"},
    {"ticker": "VIVT3", "nome": "Vivo - Telefônica Brasil", "tipo": "acao"},
    {"ticker": "VLID3", "nome": "Valid", "tipo": "acao"},
    {"ticker": "VSTE3", "nome": "Veste S/A", "tipo": "acao"},
    {"ticker": "VTRU3", "nome": "Vitru Educação", "tipo": "acao"},
    {"ticker": "VULC3", "nome": "Vulcabras", "tipo": "acao"},
    {"ticker": "WEGE3", "nome": "Weg", "tipo": "acao"},
    {"ticker": "WHRL4", "nome": "Whirlpool", "tipo": "acao"},
    {"ticker": "WIZC3", "nome": "Wiz", "tipo": "acao"},
    {"ticker": "WLMM3", "nome": "Wlm Indústria E Comércio", "tipo": "acao"},
    {"ticker": "YDUQ3", "nome": "Yduqs", "tipo": "acao"},
]

# Lista unica para o autocomplete da navbar (ordem alfabetica por ticker)
ATIVOS = sorted(FIIS + ACOES, key=lambda a: a["ticker"])

