# Lista FIXA de ativos para a busca (Dia 28)
# Gerada em 2026-07-20 09:29 a partir do Status Invest (lista completa B3).
# Nao e atualizada em runtime — rode temp/tests/gerar_ativos_lista.py para renovar.

FIIS = [
    {"ticker": "ABCP11", "nome": "Grand Plaza Shopping", "tipo": "fii"},
    {"ticker": "ADSH11", "nome": "Ad Shopping Fii Resp Limitada", "tipo": "fii"},
    {"ticker": "AFHF11", "nome": "Af Invest Real Estate Multiestratégia", "tipo": "fii"},
    {"ticker": "AFHI11", "nome": "Af Invest Cri", "tipo": "fii"},
    {"ticker": "AIEC11", "nome": "Autonomy Edifícios Corporativos", "tipo": "fii"},
    {"ticker": "AJFI11", "nome": "Aj Malls Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "ALMI11", "nome": "Torre Almirante", "tipo": "fii"},
    {"ticker": "ALZC11", "nome": "Alianza Crédito Imobilário Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "ALZM11", "nome": "Alianza Multiestratégia Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "ALZR11", "nome": "Alianza Trust Renda Imobiliária", "tipo": "fii"},
    {"ticker": "APTO11", "nome": "Navi Residencial", "tipo": "fii"},
    {"ticker": "APXM11", "nome": "Fundo De Investimento Imobiliário Apex Malls", "tipo": "fii"},
    {"ticker": "APXR11", "nome": "Apex Realty Fdo De Inv Imob Resp Ltda", "tipo": "fii"},
    {"ticker": "APXU11", "nome": "Apex Urb Fdo De Inv Imob Resp Ltda", "tipo": "fii"},
    {"ticker": "AQLL11", "nome": "Áquilla", "tipo": "fii"},
    {"ticker": "AROA11", "nome": "Aroeira 333 Renda Logística Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "ARRI11", "nome": "Átrio Reit Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "ARTE11", "nome": "Ártemis Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "ARXD11", "nome": "Arx Dover Recebíveis Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "ASRF11", "nome": "Asa Retrofits I Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "ATCR11", "nome": "HAZ", "tipo": "fii"},
    {"ticker": "ATSA11", "nome": "Hedge Atrium Shopping Santo André", "tipo": "fii"},
    {"ticker": "ATWN11", "nome": "Fdo. Inv. Imob. A–Town", "tipo": "fii"},
    {"ticker": "AURB11", "nome": "Alianza Urban Hub Renda Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "AZPE11", "nome": "Fii Azpe", "tipo": "fii"},
    {"ticker": "AZPL11", "nome": "Az Quest Panorama Logistica Fdo Inv Imob Resp Lim", "tipo": "fii"},
    {"ticker": "BARI11", "nome": "Vbi Rendimentos Imobiliários I", "tipo": "fii"},
    {"ticker": "BBFI11", "nome": "BB Progressivo", "tipo": "fii"},
    {"ticker": "BBFO11", "nome": "Bb Fundo De Fundos", "tipo": "fii"},
    {"ticker": "BBIG11", "nome": "Bb Premium Malls Fdo De Inv Imob Resp Lim", "tipo": "fii"},
    {"ticker": "BBIM11", "nome": "BB Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "BBRC11", "nome": "BB Renda Corporativa", "tipo": "fii"},
    {"ticker": "BCFF11", "nome": "BTG Fundo de Fundos", "tipo": "fii"},
    {"ticker": "BCIA11", "nome": "Bradesco Carteira Imobiliária Ativa", "tipo": "fii"},
    {"ticker": "BCRI11", "nome": "Banestes Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "BETW11", "nome": "Fii Betw", "tipo": "fii"},
    {"ticker": "BGRB11", "nome": "Bgr B32 Fundo De Invest Imob Resp Lim", "tipo": "fii"},
    {"ticker": "BICE11", "nome": "Brio Crédito Estruturado", "tipo": "fii"},
    {"ticker": "BICR11", "nome": "Inter Títulos Imob. Fdo Inv. Imob.", "tipo": "fii"},
    {"ticker": "BIME11", "nome": "Brio Multiestratégia", "tipo": "fii"},
    {"ticker": "BINR11", "nome": "Brix Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "BIPD11", "nome": "Brio Real Estate Iv", "tipo": "fii"},
    {"ticker": "BIPE11", "nome": "Fii Brio V", "tipo": "fii"},
    {"ticker": "BLCA11", "nome": "Bluemacaw Catuaí Triple A Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "BLCP11", "nome": "Bluecap Renda Log. Fdo Inv. Imob. - Fii", "tipo": "fii"},
    {"ticker": "BLMC11", "nome": "Bluemacaw Crédito Imobiliário", "tipo": "fii"},
    {"ticker": "BLMG11", "nome": "Bluemacaw Logística", "tipo": "fii"},
    {"ticker": "BLMO11", "nome": "Bluemacaw Office Fund Ii - Fdo. Invest. Imob.", "tipo": "fii"},
    {"ticker": "BLMR11", "nome": "Bluemacaw Renda + Fof", "tipo": "fii"},
    {"ticker": "BLOG11", "nome": "Bluecap Log Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "BLUR11", "nome": "Fundo De Investimento Imobiliário – Blue Recebívei", "tipo": "fii"},
    {"ticker": "BMII11", "nome": "Brasilio Machado", "tipo": "fii"},
    {"ticker": "BMLC11", "nome": "BM Brascan Lajes Corporativas", "tipo": "fii"},
    {"ticker": "BNFS11", "nome": "Banrisul Novas Fronteiras", "tipo": "fii"},
    {"ticker": "BPFF11", "nome": "Brasil Plural Absoluto Fundo de Fundos", "tipo": "fii"},
    {"ticker": "BPLC11", "nome": "Basílica Partners Led Corporate Fdo Inv Imob Fii", "tipo": "fii"},
    {"ticker": "BPML11", "nome": "Fdo Inv Imob Btg Pactual Shoppings", "tipo": "fii"},
    {"ticker": "BPRP11", "nome": "Fdo Inv Imob - Fii Brlprop", "tipo": "fii"},
    {"ticker": "BRCO11", "nome": "Bresco Logística - Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "BRCR11", "nome": "BTG Pactual Corporate Office", "tipo": "fii"},
    {"ticker": "BREV11", "nome": "Brazil Real Estate Victory Fund I", "tipo": "fii"},
    {"ticker": "BRIM11", "nome": "Brio Real Estate Ii - Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "BRIP11", "nome": "Brio Real Estate Iii", "tipo": "fii"},
    {"ticker": "BROF11", "nome": "Brpr Corporate Offices Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "BROL11", "nome": "Br Properties", "tipo": "fii"},
    {"ticker": "BRSE11", "nome": "Br7 Senado Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "BSLT11", "nome": "Fundo De Investimentos Imobiliários De Permuta Financeira Lote5 (Senior) Responsabilidade Limitada", "tipo": "fii"},
    {"ticker": "BTCI11", "nome": "Fii Btg Pactual Crédito Imobiliário", "tipo": "fii"},
    {"ticker": "BTCR11", "nome": "BTG Pactual Crédito Imobiliário", "tipo": "fii"},
    {"ticker": "BTHF11", "nome": "Btg Pactual Real Estate Hedge Fund Fii - Resp Ltda", "tipo": "fii"},
    {"ticker": "BTHI11", "nome": "Btg Pactual Hotéis Fii", "tipo": "fii"},
    {"ticker": "BTHR11", "nome": "Btg Hospitalidade Retorno Total Fundo De Investimento Imobiliario Responsabilidade Limitada", "tipo": "fii"},
    {"ticker": "BTLG11", "nome": "Btg Pactual Logistica Fdo Inv Imob - Fii", "tipo": "fii"},
    {"ticker": "BTML11", "nome": "Barra Malls Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "BTSG11", "nome": "Btsp I Fdo. Invest. Imob", "tipo": "fii"},
    {"ticker": "BTSI11", "nome": "Btsp Ii Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "BTWR11", "nome": "Btowers Fii", "tipo": "fii"},
    {"ticker": "BTYU11", "nome": "Btg Pactual You", "tipo": "fii"},
    {"ticker": "BVAR11", "nome": "Brasil Varejo", "tipo": "fii"},
    {"ticker": "BZEL11", "nome": "Barzel Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "BZLI11", "nome": "Brazil Realty", "tipo": "fii"},
    {"ticker": "CACR11", "nome": "Cartesia Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "CARE11", "nome": "Brazilian Graveyard and Death Care", "tipo": "fii"},
    {"ticker": "CBOP11", "nome": "Castello Branco Office Park", "tipo": "fii"},
    {"ticker": "CCLB11", "nome": "Fii Central Leblon", "tipo": "fii"},
    {"ticker": "CCME11", "nome": "Canuma Capital Multiestratégia Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CCRF11", "nome": "Canvas Cri", "tipo": "fii"},
    {"ticker": "CCVA11", "nome": "Canuma Capital Renda Varejo", "tipo": "fii"},
    {"ticker": "CENU11", "nome": "Cenu - Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CEOC11", "nome": "Cyrela Commercial Properties", "tipo": "fii"},
    {"ticker": "CFHI11", "nome": "Cf2 Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "CFII11", "nome": "Cf3 Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "CIXM11", "nome": "Cix Muiraquitan Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CIXR11", "nome": "Cix Rendimento Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "CJCT11", "nome": "Cidade Jardim Continenal Tower", "tipo": "fii"},
    {"ticker": "CJFI11", "nome": "Fdo Inv Imob Cj", "tipo": "fii"},
    {"ticker": "CLIN11", "nome": "Clave Índices De Preços Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CNES11", "nome": "Cenesp", "tipo": "fii"},
    {"ticker": "COPP11", "nome": "Corporate Office Properties Fii - Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CPFF11", "nome": "Capitânia Reit Fof - Fdo. Invest. Imob", "tipo": "fii"},
    {"ticker": "CPFO11", "nome": "Capitânia Reit Fof - Fdo Inv Imob Ii", "tipo": "fii"},
    {"ticker": "CPHH11", "nome": "Capitânia Reit Fof Iii Fii", "tipo": "fii"},
    {"ticker": "CPLG11", "nome": "Capitânia Logística Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CPOF11", "nome": "Capitânia Office Fii - Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CPSH11", "nome": "Shoppings Aaa Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CPTS11", "nome": "Capitania Securities II", "tipo": "fii"},
    {"ticker": "CPUR11", "nome": "Vbi Consumo Essen", "tipo": "fii"},
    {"ticker": "CRFF11", "nome": "Caixa Rio Bravo Fdo De Fdos Inv Imob Ii", "tipo": "fii"},
    {"ticker": "CSMC11", "nome": "Cosmic Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "CTEM11", "nome": "Caetê Fiagro - Direitos Creditórios", "tipo": "fii"},
    {"ticker": "CTNP11", "nome": "Constantinopla Recebíveis Imobiliários Fii", "tipo": "fii"},
    {"ticker": "CTXT11", "nome": "Centro Têxtil Internacional", "tipo": "fii"},
    {"ticker": "CVPR11", "nome": "Cvpar Fundo De Investimento Imobiliário De Cri", "tipo": "fii"},
    {"ticker": "CXAG11", "nome": "Fii Caixa Agências", "tipo": "fii"},
    {"ticker": "CXCE11", "nome": "Caixa Cedae", "tipo": "fii"},
    {"ticker": "CXCI11", "nome": "Fdo De Invst Imob Caixa Carteira Imobiliária", "tipo": "fii"},
    {"ticker": "CXCO11", "nome": "Fdo. Inv. Imob. Caixa Imóveis Corporativos", "tipo": "fii"},
    {"ticker": "CXRI11", "nome": "Caixa Rio Bravo", "tipo": "fii"},
    {"ticker": "CXTL11", "nome": "Caixa TRX Logística Renda", "tipo": "fii"},
    {"ticker": "CYCR11", "nome": "Cyrela Crédito", "tipo": "fii"},
    {"ticker": "CYLD11", "nome": "Cyrela Desenvolvimento Logístico Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "DAMA11", "nome": "Dama Fundo De Investimento Imobiliário Resp Limita", "tipo": "fii"},
    {"ticker": "DAYM11", "nome": "Daycoval Real Estate Multiestratégia FII", "tipo": "fii"},
    {"ticker": "DEVA11", "nome": "Devant Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "DLMT11", "nome": "Del Monte Ajax Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "DMAC11", "nome": "Mac Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "DOMC11", "nome": "Reag Renda Imobiliária", "tipo": "fii"},
    {"ticker": "DPRO11", "nome": "Devant Properties Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "DRIT11", "nome": "Multigestão Renda Comercial", "tipo": "fii"},
    {"ticker": "DVFF11", "nome": "Fdo. Invest. Imob. Devant Fof Imobiliários", "tipo": "fii"},
    {"ticker": "DVLP11", "nome": "Speciale Real Estate Development Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "DVLT11", "nome": "Fii Dvlt", "tipo": "fii"},
    {"ticker": "EAGL11", "nome": "Fii Eagl", "tipo": "fii"},
    {"ticker": "EDFO11", "nome": "Edifício Ouroinvest", "tipo": "fii"},
    {"ticker": "EDGA11", "nome": "Edifício Galeria", "tipo": "fii"},
    {"ticker": "EDGE11", "nome": "Fii Edge", "tipo": "fii"},
    {"ticker": "EGDB11", "nome": "Fii Egdb", "tipo": "fii"},
    {"ticker": "EGYR11", "nome": "Energy Resort Fdo. Invest. Imob", "tipo": "fii"},
    {"ticker": "EIRA11", "nome": "Aroeira Fundo De Investimento Imobiliário - Responsabilidade Limitada", "tipo": "fii"},
    {"ticker": "ELDO11", "nome": "Eldorado", "tipo": "fii"},
    {"ticker": "EMET11", "nome": "Emet Multiestratégia Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "EQIR11", "nome": "Eqi Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "ERCR11", "nome": "Estoque Residencial E Comercial Rj", "tipo": "fii"},
    {"ticker": "ERPA11", "nome": "Europa 105 - Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "ESTQ11", "nome": "Fdo Inv Imob Polo Estoque Ii", "tipo": "fii"},
    {"ticker": "EURO11", "nome": "Europar", "tipo": "fii"},
    {"ticker": "EXES11", "nome": "Exes Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "FAED11", "nome": "Anhanguera Educacional", "tipo": "fii"},
    {"ticker": "FAGL11", "nome": "Fator Renda Galpão Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "FAMB11", "nome": "Edifício Almirante Barroso", "tipo": "fii"},
    {"ticker": "FAOE11", "nome": "Fator Renda Estruturada", "tipo": "fii"},
    {"ticker": "FARU11", "nome": "Fator Renda Urbana Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "FATN11", "nome": "BRC Renda Corporativa Fundo de Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "FCAS11", "nome": "Edifício Castelo", "tipo": "fii"},
    {"ticker": "FCFL11", "nome": "Campus Faria Lima", "tipo": "fii"},
    {"ticker": "FGPM11", "nome": "Fdo Invest Imob Grand Plaza Mall", "tipo": "fii"},
    {"ticker": "FIGS11", "nome": "General Shopping Ativo e Renda", "tipo": "fii"},
    {"ticker": "FIIB11", "nome": "Industrial do Brasil", "tipo": "fii"},
    {"ticker": "FIIC11", "nome": "Fii Fiic", "tipo": "fii"},
    {"ticker": "FIIP11", "nome": "RB Capital Renda I", "tipo": "fii"},
    {"ticker": "FINF11", "nome": "Infra Real State", "tipo": "fii"},
    {"ticker": "FISC11", "nome": "Fdo Inv Imob Sc 401", "tipo": "fii"},
    {"ticker": "FISD11", "nome": "São Domingos", "tipo": "fii"},
    {"ticker": "FIVN11", "nome": "Vida Nova", "tipo": "fii"},
    {"ticker": "FLCR11", "nome": "Faria Lima Capital Receb. Imob. I", "tipo": "fii"},
    {"ticker": "FLFL11", "nome": "Vbi Tr Faria Lima 4440 Fii", "tipo": "fii"},
    {"ticker": "FLMA11", "nome": "Continental Square Faria Lima", "tipo": "fii"},
    {"ticker": "FLNR11", "nome": "Fii Flnr", "tipo": "fii"},
    {"ticker": "FLRP11", "nome": "Floripa Shopping", "tipo": "fii"},
    {"ticker": "FMOF11", "nome": "Memorial Office", "tipo": "fii"},
    {"ticker": "FOFT11", "nome": "Hedge TOP FOFII 2", "tipo": "fii"},
    {"ticker": "FPAB11", "nome": "Projeto Água Branca", "tipo": "fii"},
    {"ticker": "FPNG11", "nome": "Pedra Negra Renda Imobiliária", "tipo": "fii"},
    {"ticker": "FRHY11", "nome": "Fronteira Multi Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "FVBI11", "nome": "Vbi Fl 4440", "tipo": "fii"},
    {"ticker": "FVPQ11", "nome": "Via Parque Shopping", "tipo": "fii"},
    {"ticker": "FYTO11", "nome": "Fii Nch Brasil Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "GAME11", "nome": "Fdo De Invest Imob Guardian Multiestratégia I", "tipo": "fii"},
    {"ticker": "GARE11", "nome": "Guardian Real Estate", "tipo": "fii"},
    {"ticker": "GCDL11", "nome": "Fii Gcdl", "tipo": "fii"},
    {"ticker": "GCFF11", "nome": "Galapagos Fdo De Fdo - Fii Fdo Inv. Imob.", "tipo": "fii"},
    {"ticker": "GCOI11", "nome": "Galapagos Special Oportunities Fii", "tipo": "fii"},
    {"ticker": "GCRI11", "nome": "Galapagos Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "GFDL11", "nome": "Galapagos Feeder Des Log Fii Resp Lim", "tipo": "fii"},
    {"ticker": "GGRC11", "nome": "Zagros Renda Imobiliária", "tipo": "fii"},
    {"ticker": "GLCR11", "nome": "Galapagos Crédito Estruturado", "tipo": "fii"},
    {"ticker": "GLOG11", "nome": "Plural Logística Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "GLPF11", "nome": "Fii Glpf", "tipo": "fii"},
    {"ticker": "GLPL11", "nome": "Glp Logística", "tipo": "fii"},
    {"ticker": "GRLV11", "nome": "CSHG GR Louveira", "tipo": "fii"},
    {"ticker": "GRUL11", "nome": "Fii Grul", "tipo": "fii"},
    {"ticker": "GSFI11", "nome": "General Shop E Outlets Do Brasil Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "GTLG11", "nome": "Gtis Brazil Logistics", "tipo": "fii"},
    {"ticker": "GTWR11", "nome": "Fdo Inv Imob Green Towers", "tipo": "fii"},
    {"ticker": "GURB11", "nome": "Genial Renda Urbana Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "GVBI11", "nome": "Fundo De Investimento Imobiliário – Vbi Greenpower", "tipo": "fii"},
    {"ticker": "GZIT11", "nome": "Gazit Malls Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "HAAA11", "nome": "Hedge Aaa", "tipo": "fii"},
    {"ticker": "HABT11", "nome": "Habitat Recebíveis Pulverizados", "tipo": "fii"},
    {"ticker": "HBCR11", "nome": "Hbc Renda Urbana", "tipo": "fii"},
    {"ticker": "HBTT11", "nome": "Habitat I", "tipo": "fii"},
    {"ticker": "HCHG11", "nome": "Hectare Recebíveis High Grade", "tipo": "fii"},
    {"ticker": "HCPR11", "nome": "Hectare Properties Fdo De Inv Imob - Fii", "tipo": "fii"},
    {"ticker": "HCRI11", "nome": "Hospital da Criança", "tipo": "fii"},
    {"ticker": "HCST11", "nome": "Hectare Desenv. Student Housing", "tipo": "fii"},
    {"ticker": "HCTR11", "nome": "Hectare Ce - Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "HDEL11", "nome": "Hedge Desenvolvimento Logístico Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "HDOF11", "nome": "Hedge Desenvolvimento Logístico Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "HFOF11", "nome": "Hedge Top FOFII 3", "tipo": "fii"},
    {"ticker": "HGBL11", "nome": "Hedge Brasil Logístico Ind Fund Inv Imob Resp Lim", "tipo": "fii"},
    {"ticker": "HGBS11", "nome": "Hedge Brasil Shopping", "tipo": "fii"},
    {"ticker": "HGCR11", "nome": "Pátria Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "HGFF11", "nome": "Cshg Imob. Fof - Fdo Inv. Imob. - Fii", "tipo": "fii"},
    {"ticker": "HGIC11", "nome": "Hgi Créditos Imobiliários", "tipo": "fii"},
    {"ticker": "HGLG11", "nome": "Pátria Log", "tipo": "fii"},
    {"ticker": "HGPO11", "nome": "Cshg Prime Offices Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "HGRE11", "nome": "Pátria Escritórios", "tipo": "fii"},
    {"ticker": "HGRS11", "nome": "Cshg Residencial Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "HGRU11", "nome": "Pátria Renda Urbana", "tipo": "fii"},
    {"ticker": "HILG11", "nome": "Hire Log I Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "HIRE11", "nome": "Hire Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "HLMB11", "nome": "Fram Capital Helmer Multi Renda Pref Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "HLOG11", "nome": "Hedge Logística Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "HMOC11", "nome": "Hedge Shopping Praça da Moça", "tipo": "fii"},
    {"ticker": "HOFC11", "nome": "Hedge Office Income Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "HOMS11", "nome": "Fii Homs", "tipo": "fii"},
    {"ticker": "HOSI11", "nome": "Fdo. Inv. Imob. Housi", "tipo": "fii"},
    {"ticker": "HPDP11", "nome": "Hedge Shopping Parque Dom Pedro", "tipo": "fii"},
    {"ticker": "HPDR11", "nome": "Hedge Paladin Desenvolvimento Residencial Fundo De Investimento Imobiliario De Responsabilidade Ltda", "tipo": "fii"},
    {"ticker": "HRDF11", "nome": "Hedge Realty Development Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "HREC11", "nome": "Hedge Recebiveis Imob", "tipo": "fii"},
    {"ticker": "HRES11", "nome": "Fii Hire Res", "tipo": "fii"},
    {"ticker": "HSAF11", "nome": "Hsi Ativos Financeiros", "tipo": "fii"},
    {"ticker": "HSLG11", "nome": "Hsi Logística", "tipo": "fii"},
    {"ticker": "HSML11", "nome": "Hsi Mall Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "HSRE11", "nome": "Hsi Renda Imob", "tipo": "fii"},
    {"ticker": "HTMX11", "nome": "Hotel Maxinvest", "tipo": "fii"},
    {"ticker": "HUCG11", "nome": "Fdo Inv Imob Hospital Unimed Campina Grande", "tipo": "fii"},
    {"ticker": "HUSC11", "nome": "Hospital Unimed Sul Capixaba", "tipo": "fii"},
    {"ticker": "HUSI11", "nome": "Husi Fdo Inv. Imob.", "tipo": "fii"},
    {"ticker": "HYPI11", "nome": "Fii Hypi", "tipo": "fii"},
    {"ticker": "IBBP11", "nome": "Fii Ibbp", "tipo": "fii"},
    {"ticker": "IBCR11", "nome": "Fdo De Inv Imobiliário De Cri Integral Brei", "tipo": "fii"},
    {"ticker": "IBFF11", "nome": "Fdo Inv. Imob. Fof Integral Brei", "tipo": "fii"},
    {"ticker": "ICNE11", "nome": "Ícone - Fundo De Invest Imob Res Limitada", "tipo": "fii"},
    {"ticker": "ICRI11", "nome": "Itaú Crédito Imob Ipca Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "IDFI11", "nome": "Fdo Inv Imobiliário De Unidades Autônomas", "tipo": "fii"},
    {"ticker": "IDGR11", "nome": "Fdo De Inv Imobiliário De Unidades Autônomas Ii", "tipo": "fii"},
    {"ticker": "IDUA11", "nome": "Fdo De Inv Imobiliário De Unidades Autônomas Iv", "tipo": "fii"},
    {"ticker": "IMOV11", "nome": "Navi Hedge Fund", "tipo": "fii"},
    {"ticker": "INDE11", "nome": "Inter Desenvolvimento Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "INLG11", "nome": "Inter Log Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "INRD11", "nome": "Inter Residence Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "IRDM11", "nome": "Iridium Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "IRIM11", "nome": "Iridium Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "ISCJ11", "nome": "Invista Scj - Fii", "tipo": "fii"},
    {"ticker": "ITIP11", "nome": "Inter Teva Indice De Papel Fundo De Investimento", "tipo": "fii"},
    {"ticker": "ITIT11", "nome": "Inter Teve Indice De Tijolo Fundo De Investimento", "tipo": "fii"},
    {"ticker": "ITRI11", "nome": "Itaú Total Return Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "IVCI11", "nome": "Fii Ivci", "tipo": "fii"},
    {"ticker": "JASC11", "nome": "Jasc Renda Varejo Essencial Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "JBFO11", "nome": "Jbfo Fof Fdo Inv. Imob.", "tipo": "fii"},
    {"ticker": "JCCJ11", "nome": "Jhsf Capital Cidade Jardim – Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "JCDA11", "nome": "Jacarandá I Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "JCDB11", "nome": "Jacarandá 02 Fundo De Investimento Imobiliário Fii", "tipo": "fii"},
    {"ticker": "JCIN11", "nome": "Fii Jcin", "tipo": "fii"},
    {"ticker": "JFLL11", "nome": "Jfl Living Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "JPPA11", "nome": "Jpp Allocation Mogno - Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "JPPC11", "nome": "JPP Capital", "tipo": "fii"},
    {"ticker": "JRDM11", "nome": "Shopping Jardim Sul", "tipo": "fii"},
    {"ticker": "JSAF11", "nome": "Js Ativos Financeiros", "tipo": "fii"},
    {"ticker": "JSCR11", "nome": "Fii Jscr", "tipo": "fii"},
    {"ticker": "JSRE11", "nome": "JS Real Estate Multigestão", "tipo": "fii"},
    {"ticker": "JTPR11", "nome": "JT Prev FII Desenvolvimento Habitacional", "tipo": "fii"},
    {"ticker": "KCRE11", "nome": "Kinea Creditas Fdo De Inv Imobiliário", "tipo": "fii"},
    {"ticker": "KEVE11", "nome": "Even Ii Kinea", "tipo": "fii"},
    {"ticker": "KFEN11", "nome": "Kinea Fênix", "tipo": "fii"},
    {"ticker": "KFOF11", "nome": "Fundo De Fdo Inv Imob Kinea Fii", "tipo": "fii"},
    {"ticker": "KINP11", "nome": "Even Permuta Kinea", "tipo": "fii"},
    {"ticker": "KISU11", "nome": "Kilima Fic Fdo. Imob. Suno 30", "tipo": "fii"},
    {"ticker": "KIVO11", "nome": "Kilima Volkano Recebíveis Imob Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "KLOG11", "nome": "Fii Kinea Dl", "tipo": "fii"},
    {"ticker": "KNCR11", "nome": "Kinea Rendimentos Imobiliários", "tipo": "fii"},
    {"ticker": "KNHF11", "nome": "Kinea Hedge Fund Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "KNHY11", "nome": "Kinea High Yield CRI", "tipo": "fii"},
    {"ticker": "KNIP11", "nome": "Kinea Índice de Preços", "tipo": "fii"},
    {"ticker": "KNPR11", "nome": "Kinea Premium Properties Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "KNRE11", "nome": "Kinea II Real Estate Equity", "tipo": "fii"},
    {"ticker": "KNRI11", "nome": "Kinea Renda Imobiliária", "tipo": "fii"},
    {"ticker": "KNSC11", "nome": "Kinea Securities Fdo. De Inv. Imob. - Fii", "tipo": "fii"},
    {"ticker": "KNUQ11", "nome": "Kinea Unique Hy Cdi Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "KOPI11", "nome": "Kinea Opor Imob I Fundo De Invest Imb Ltda", "tipo": "fii"},
    {"ticker": "KORE11", "nome": "Kinea Oportunidades Real Estate Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "KRES11", "nome": "Kinea Aquisições Residenciais Fii Resp Lim", "tipo": "fii"},
    {"ticker": "LASC11", "nome": "Legatus Shoppings Fdo. Inv. Imob. - Fii", "tipo": "fii"},
    {"ticker": "LAVF11", "nome": "Lavoura Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "LFTT11", "nome": "Loft Ii Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "LIFE11", "nome": "Life Capital Partners Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "LKDV11", "nome": "Fundo De Investimento Imobiliário Development", "tipo": "fii"},
    {"ticker": "LLAO11", "nome": "Bs2 Allinvestments Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "LMAI11", "nome": "Labina Multi Ativos Imobiliários", "tipo": "fii"},
    {"ticker": "LPLP11", "nome": "Lago Da Pedra", "tipo": "fii"},
    {"ticker": "LRDI11", "nome": "Fdo De Inv Imob Leblon Realty Desenvolvimento I", "tipo": "fii"},
    {"ticker": "LRED11", "nome": "LCP Real Estate Development", "tipo": "fii"},
    {"ticker": "LSOI11", "nome": "Lcp Special Opportunities I Fdo Inv Imob Resp", "tipo": "fii"},
    {"ticker": "LSPA11", "nome": "Leste Riva Equity Preferencial I", "tipo": "fii"},
    {"ticker": "LTMT11", "nome": "Fii Speciale", "tipo": "fii"},
    {"ticker": "LVBI11", "nome": "Fdo Inv Imob - Vbi Logístico", "tipo": "fii"},
    {"ticker": "MADS11", "nome": "Mauá Capital Desenv I", "tipo": "fii"},
    {"ticker": "MAGM11", "nome": "Mag Ativos Imobiliários Multiestratégia Classe De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "MANA11", "nome": "Manatí Capital Hedge Fund Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "MATV11", "nome": "More Gestão Ativa", "tipo": "fii"},
    {"ticker": "MAXR11", "nome": "Max Retail", "tipo": "fii"},
    {"ticker": "MCCI11", "nome": "Fdo Inv. Maua Capital Recebiveis Imob. - Fii", "tipo": "fii"},
    {"ticker": "MCEM11", "nome": "Mérito Cemitérios Fii - Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "MCHF11", "nome": "Mauá Capital Hedge Fund", "tipo": "fii"},
    {"ticker": "MCLO11", "nome": "Maua Capital Logistica Fii", "tipo": "fii"},
    {"ticker": "MCRE11", "nome": "Fdo De Inv Imob Mauá Capital High Yield - Fii", "tipo": "fii"},
    {"ticker": "MFAI11", "nome": "Merito Fdo. Ações Imob. Fii - Fdo Inv. Imob.", "tipo": "fii"},
    {"ticker": "MFCR11", "nome": "Mérito Recebíveis Imobiliários Fii", "tipo": "fii"},
    {"ticker": "MFII11", "nome": "Mérito Desenvolvimento Imobiliário", "tipo": "fii"},
    {"ticker": "MGCR11", "nome": "Mogno Cri High Grade", "tipo": "fii"},
    {"ticker": "MGFF11", "nome": "Mogno Fundo de Fundos", "tipo": "fii"},
    {"ticker": "MGHT11", "nome": "Fdo. Inv. Imob. Mogno Hoteis", "tipo": "fii"},
    {"ticker": "MGIM11", "nome": "Mogno Real Estate Impact Dev. Fund", "tipo": "fii"},
    {"ticker": "MGLC11", "nome": "Mogno Properties", "tipo": "fii"},
    {"ticker": "MGRI11", "nome": "Mogno Properties Fundo De Investimento Imobiliario", "tipo": "fii"},
    {"ticker": "MINT11", "nome": "Mint Educacional", "tipo": "fii"},
    {"ticker": "MMPD11", "nome": "Fdo De Inv Imob Maua Capital Mpd Desenv Resid", "tipo": "fii"},
    {"ticker": "MMVE11", "nome": "Mmve Oportunidades Imobiliárias", "tipo": "fii"},
    {"ticker": "MOFF11", "nome": "Multioffices 2 - Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "MORC11", "nome": "More Recebíveis Imobiliários Fii", "tipo": "fii"},
    {"ticker": "MORE11", "nome": "More Real Estate Fof Fii Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "MOSO11", "nome": "Moso Fundo De Investimento Imobiliário Responsabilidade Limitada", "tipo": "fii"},
    {"ticker": "MTOF11", "nome": "Multioffices 1", "tipo": "fii"},
    {"ticker": "MTRS11", "nome": "Fdo Inv Imob - Btg Pactual Metropolis", "tipo": "fii"},
    {"ticker": "MVFI11", "nome": "Fdo Inv Imob Mv9", "tipo": "fii"},
    {"ticker": "MXRF11", "nome": "Maxi Renda", "tipo": "fii"},
    {"ticker": "N4V111", "nome": "Fii Intermediário Navi Tot", "tipo": "fii"},
    {"ticker": "NAUI11", "nome": "Fii Naui", "tipo": "fii"},
    {"ticker": "NAVT11", "nome": "Navi Imobiliário Total Return", "tipo": "fii"},
    {"ticker": "NCRI11", "nome": "Navi Crédito Imobiliário", "tipo": "fii"},
    {"ticker": "NEWL11", "nome": "Newport Logística", "tipo": "fii"},
    {"ticker": "NEWU11", "nome": "Newport Renda Urbana Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "NIVT11", "nome": "Onda Invest Multiestratégia Fii", "tipo": "fii"},
    {"ticker": "NPAR11", "nome": "Onda Invest Multiestratégia Fii", "tipo": "fii"},
    {"ticker": "NSLU11", "nome": "Hospital Nossa Sra Lourdes", "tipo": "fii"},
    {"ticker": "NVHO11", "nome": "Novo Horizonte", "tipo": "fii"},
    {"ticker": "NVIF11", "nome": "Fii Nova I", "tipo": "fii"},
    {"ticker": "OBAL11", "nome": "Fii Oppbal", "tipo": "fii"},
    {"ticker": "OCRE11", "nome": "Octo Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "OGHY11", "nome": "Órama High Yield Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "ONDA11", "nome": "Onda Invest Multiestratégia Fii", "tipo": "fii"},
    {"ticker": "ONEF11", "nome": "The One", "tipo": "fii"},
    {"ticker": "OPTM11", "nome": "Fundo De Investimento Imobiliario Patrimonial Iv", "tipo": "fii"},
    {"ticker": "ORPD11", "nome": "Ouro Preto Desenvolvimento Imobiliário I", "tipo": "fii"},
    {"ticker": "OUFF11", "nome": "Fdo Inv Imob - Ourinvest Fundo De Fundos", "tipo": "fii"},
    {"ticker": "OUJP11", "nome": "Ourinvest Jpp", "tipo": "fii"},
    {"ticker": "OURE11", "nome": "Ourinvest Cyrela", "tipo": "fii"},
    {"ticker": "PABY11", "nome": "Panamby", "tipo": "fii"},
    {"ticker": "PATA11", "nome": "Patagônia Capital Multiestratégia Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "PATB11", "nome": "Fdo Inv Imob - Fii Pateo Bandeirantes", "tipo": "fii"},
    {"ticker": "PATC11", "nome": "Pátria Edifícios Corporativos Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "PATL11", "nome": "Pátria Logística", "tipo": "fii"},
    {"ticker": "PBLV11", "nome": "Prologis Brazil Logistics Venture Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "PCAS11", "nome": "Praia Do Castelo Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "PCIP11", "nome": "Patria Crédito Imobiliário Índice de Preços Fundo de Investimento Imobiliário - Responsabilidade Limitada", "tipo": "fii"},
    {"ticker": "PDBM11", "nome": "Pdb Malls Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "PEMA11", "nome": "Performa Real Estate", "tipo": "fii"},
    {"ticker": "PLAG11", "nome": "Quasar Agro - Fdo Inv. Imob.", "tipo": "fii"},
    {"ticker": "PLCR11", "nome": "Fdo Inv. Imob. Plural Recebiveis", "tipo": "fii"},
    {"ticker": "PLRI11", "nome": "Polo Recebíveis Imobiliários I", "tipo": "fii"},
    {"ticker": "PMFO11", "nome": "Speciale Real Estate Fund Of Funds Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "PMIS11", "nome": "Paramis Hedge Fund Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "PMLL11", "nome": "Patria Malls FII", "tipo": "fii"},
    {"ticker": "PMRL11", "nome": "Permuta Residencial Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "PNCR11", "nome": "Panorama Credito Residencial Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "PNDL11", "nome": "Panorama Desenvolvimento Logístico", "tipo": "fii"},
    {"ticker": "PNLN11", "nome": "Panorama Last Mile Sbc Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "PNPR11", "nome": "Panorama Properties Fdo. Invest. Imob.", "tipo": "fii"},
    {"ticker": "PNRC11", "nome": "Panorama Real Estate Crédito Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "PORD11", "nome": "Polo Crédito Imobiliário", "tipo": "fii"},
    {"ticker": "PQAG11", "nome": "Parque Anhanguera Fdo. Invest. Imob.", "tipo": "fii"},
    {"ticker": "PQDP11", "nome": "Parque Dom Pedro Shopping Center", "tipo": "fii"},
    {"ticker": "PRSV11", "nome": "Presidente Vargas", "tipo": "fii"},
    {"ticker": "PRTS11", "nome": "Multi Properties FII", "tipo": "fii"},
    {"ticker": "PRZS11", "nome": "Prazo - Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "PSEC11", "nome": "Pátria Securities - Fdo. Inv. Imob", "tipo": "fii"},
    {"ticker": "PULV11", "nome": "Fundo De Inv Imob Rbr Créd Pulverizado Resp Ltda", "tipo": "fii"},
    {"ticker": "PVBI11", "nome": "Fdo. Inv. Imob. Vbi Prime Properties", "tipo": "fii"},
    {"ticker": "QAMI11", "nome": "Quasar Crédito Imobiliário", "tipo": "fii"},
    {"ticker": "QIRI11", "nome": "Quata Imob Recebíveis Imob", "tipo": "fii"},
    {"ticker": "QNTS11", "nome": "Fii Quintas", "tipo": "fii"},
    {"ticker": "QTZD11", "nome": "Fii Qtzd", "tipo": "fii"},
    {"ticker": "RBBV11", "nome": "JHSF Rio Bravo Fazenda Boa Vista", "tipo": "fii"},
    {"ticker": "RBCB11", "nome": "Rio Bravo Crédito Imobiliário I", "tipo": "fii"},
    {"ticker": "RBDS11", "nome": "RB Capital Desenvolvimento Residencial II", "tipo": "fii"},
    {"ticker": "RBED11", "nome": "Rio Bravo Renda Educacional", "tipo": "fii"},
    {"ticker": "RBFM11", "nome": "Fii Riob Mt", "tipo": "fii"},
    {"ticker": "RBFY11", "nome": "Fii Rio Bravo For You", "tipo": "fii"},
    {"ticker": "RBGS11", "nome": "RB Capital General Shopping Sulacap", "tipo": "fii"},
    {"ticker": "RBHG11", "nome": "Rio Bravo Credito Imob High Grade", "tipo": "fii"},
    {"ticker": "RBHY11", "nome": "Rio Bravo Crédito Imob. High Yield", "tipo": "fii"},
    {"ticker": "RBIR11", "nome": "Rb Capital Desenv. Residencial Iv", "tipo": "fii"},
    {"ticker": "RBLG11", "nome": "Rb Capital Logístico", "tipo": "fii"},
    {"ticker": "RBOP11", "nome": "Rio Bravo Oportunidades Imobiliárias Fii", "tipo": "fii"},
    {"ticker": "RBRD11", "nome": "RB Capital Renda II", "tipo": "fii"},
    {"ticker": "RBRF11", "nome": "Rbr Alpha Multiestratégia Real Estate", "tipo": "fii"},
    {"ticker": "RBRI11", "nome": "Fii Rbr Desenv", "tipo": "fii"},
    {"ticker": "RBRK11", "nome": "Rbr Prime Offices - Fundo De Investimento Imobiliário Responsabilidade Limitada", "tipo": "fii"},
    {"ticker": "RBRL11", "nome": "Rbr Log Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "RBRM11", "nome": "Fdo Inv Imob - Fii Rbr Desenvolvimento", "tipo": "fii"},
    {"ticker": "RBRP11", "nome": "RBR Properties", "tipo": "fii"},
    {"ticker": "RBRR11", "nome": "RBR Rendimento High Grade", "tipo": "fii"},
    {"ticker": "RBRS11", "nome": "Rio Bravo Renda Residencial Fdo. Invest. Imob.", "tipo": "fii"},
    {"ticker": "RBRU11", "nome": "Rb Capital Renda Urbana", "tipo": "fii"},
    {"ticker": "RBRX11", "nome": "Rbr Plus Multiestratégia Real Estate Fii", "tipo": "fii"},
    {"ticker": "RBRY11", "nome": "RBR Crédito Imobiliário Estruturado", "tipo": "fii"},
    {"ticker": "RBTS11", "nome": "Rb Capital Tfo Situs Fdo Inv Imob - Fii", "tipo": "fii"},
    {"ticker": "RBVA11", "nome": "Rio Bravo Renda Varejo", "tipo": "fii"},
    {"ticker": "RBVO11", "nome": "Rio Bravo Crédito Imobiliário II", "tipo": "fii"},
    {"ticker": "RCFA11", "nome": "Grupo Rcfa Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "RCFF11", "nome": "Rbr Desenv Comercial Feeder", "tipo": "fii"},
    {"ticker": "RCKF11", "nome": "Rock – Fii Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "RCRB11", "nome": "Fdo Inv Imob Rio Bravo Renda Corporativa", "tipo": "fii"},
    {"ticker": "RCRI11", "nome": "Real Investor Recebíveis Imobiliários - Fii", "tipo": "fii"},
    {"ticker": "RDCI11", "nome": "Fii Rdci", "tipo": "fii"},
    {"ticker": "RDIV11", "nome": "Fii Rbrdesiv", "tipo": "fii"},
    {"ticker": "RDLI11", "nome": "Rbr Desenvolvimento Logístico I - Fii Resp Limitad", "tipo": "fii"},
    {"ticker": "RDLS11", "nome": "Jgp Desenvolvimento I Fdo Inv Imob Resp Limit", "tipo": "fii"},
    {"ticker": "RECD11", "nome": "Fii Recd", "tipo": "fii"},
    {"ticker": "RECH11", "nome": "Rec Hotelaria", "tipo": "fii"},
    {"ticker": "RECM11", "nome": "Fii Recm", "tipo": "fii"},
    {"ticker": "RECR11", "nome": "FII REC Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "RECT11", "nome": "Fdo Inv Imob - Fii Rec Renda Imobiliaria", "tipo": "fii"},
    {"ticker": "RECX11", "nome": "Fdo. Inv. Imob. Rec Fundo De Fundos", "tipo": "fii"},
    {"ticker": "REIT11", "nome": "Socopa Fundo de Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "RELG11", "nome": "Rec Logistica", "tipo": "fii"},
    {"ticker": "REME11", "nome": "Rb Multiestratégia Imobiliária Fii", "tipo": "fii"},
    {"ticker": "RENV11", "nome": "Cpv Energia Fdo De Inv Imob Resp Lim", "tipo": "fii"},
    {"ticker": "RFOF11", "nome": "Rb Capital", "tipo": "fii"},
    {"ticker": "RINV11", "nome": "Real Investor Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "RJDA11", "nome": "Rjdi Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "RMBS11", "nome": "Rec Master Cri Cotas Amortizáveis Fii Rl", "tipo": "fii"},
    {"ticker": "RNDP11", "nome": "BB Renda de Papéis Imobiliários", "tipo": "fii"},
    {"ticker": "RNGO11", "nome": "Rio Negro", "tipo": "fii"},
    {"ticker": "ROOF11", "nome": "Fundo De Investimento Imobiliário Rooftop I", "tipo": "fii"},
    {"ticker": "RPRI11", "nome": "Rbr Premium Recebíveis Imobiliários Fdo Inv Imo", "tipo": "fii"},
    {"ticker": "RSPD11", "nome": "Rb Capital Desenv Resid Iii Fdo Inv Imob - Fii", "tipo": "fii"},
    {"ticker": "RTEL11", "nome": "Brc - Ii Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "RZAK11", "nome": "Riza Akin", "tipo": "fii"},
    {"ticker": "RZAT11", "nome": "Riza Arctium Real Estate Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "RZDM11", "nome": "Riza Domus Multiestratégia Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "RZLC11", "nome": "Fii Rzlc", "tipo": "fii"},
    {"ticker": "RZTR11", "nome": "Fundo De Investimento Imobiliário Riza Terrax", "tipo": "fii"},
    {"ticker": "RZZI11", "nome": "Raizz Desenvolvimento Ii Fii Resp. Limitada", "tipo": "fii"},
    {"ticker": "RZZR11", "nome": "Raizz Renda Logística Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "RZZV11", "nome": "Raizz Desenvolvimento I Fii Resp Lim", "tipo": "fii"},
    {"ticker": "SACL11", "nome": "São Carlos Renda Imobiliária Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "SADI11", "nome": "Santander Papeis Imob Cdi Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "SALI11", "nome": "Venus - Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "SAPI11", "nome": "Santander Caceis", "tipo": "fii"},
    {"ticker": "SARE11", "nome": "Santander Renda De Aluguéis Fdo. Invest. Imob.", "tipo": "fii"},
    {"ticker": "SBCL11", "nome": "Fram Capital Sbclog", "tipo": "fii"},
    {"ticker": "SCPF11", "nome": "SCP", "tipo": "fii"},
    {"ticker": "SEED11", "nome": "Hedge Seed Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "SEQR11", "nome": "Sequoia Iii Renda Imobiliária", "tipo": "fii"},
    {"ticker": "SFND11", "nome": "São Fernando", "tipo": "fii"},
    {"ticker": "SFRO11", "nome": "Csão Francisco 34", "tipo": "fii"},
    {"ticker": "SHOP11", "nome": "Multi Shoppings", "tipo": "fii"},
    {"ticker": "SHPH11", "nome": "Shopping Patio Higienopolis", "tipo": "fii"},
    {"ticker": "SHPP11", "nome": "Shopping Patio Paulista Fundo De Investimento Imobiliario Responsabilidade Limitada", "tipo": "fii"},
    {"ticker": "SHSO11", "nome": "Sh Special Opps Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "SIGR11", "nome": "Sig Capital Recebíveis Pulverizados", "tipo": "fii"},
    {"ticker": "SJAU11", "nome": "Sj Au Logística", "tipo": "fii"},
    {"ticker": "SLDZ11", "nome": "Fii Lav Sldz", "tipo": "fii"},
    {"ticker": "SMRE11", "nome": "Fdo Inv Imob Smart Real Estate - Fii Resp Limitada", "tipo": "fii"},
    {"ticker": "SNCI11", "nome": "Suno Recebíveis Imobiliários Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "SNEL11", "nome": "Fundo De Invest Imobiliario Suno Energias Limpas", "tipo": "fii"},
    {"ticker": "SNFF11", "nome": "Suno Fundo De Fundos", "tipo": "fii"},
    {"ticker": "SNLG11", "nome": "Suno Log Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "SNME11", "nome": "Suno Multiestratégia Fii", "tipo": "fii"},
    {"ticker": "SOFF11", "nome": "Fundo De Investimento Imobiliário Sofia", "tipo": "fii"},
    {"ticker": "SOLR11", "nome": "Solarium Fii", "tipo": "fii"},
    {"ticker": "SPAF11", "nome": "SPA Fundo de Investimento Imobiliário – FII", "tipo": "fii"},
    {"ticker": "SPDE11", "nome": "Whg Finvest Sp Realty Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "SPGM11", "nome": "Fii Spgm", "tipo": "fii"},
    {"ticker": "SPMO11", "nome": "Supremo Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "SPTW11", "nome": "SP Downtown", "tipo": "fii"},
    {"ticker": "SPVJ11", "nome": "Fund. Invest. Imob. Succespar Varejo", "tipo": "fii"},
    {"ticker": "SPXC11", "nome": "Fii Imobiliário Spx Syn Crédito Imob Resp Ltda", "tipo": "fii"},
    {"ticker": "SPXG11", "nome": "Spx Syn Desenvolvimento Feeder Private", "tipo": "fii"},
    {"ticker": "SPXL11", "nome": "Fii Spxl", "tipo": "fii"},
    {"ticker": "SPXS11", "nome": "Spx Syn Mult", "tipo": "fii"},
    {"ticker": "SRVD11", "nome": "Serra Verde Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "STRX11", "nome": "Starx Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "SURE11", "nome": "Sulamérica Real Estate Fundo De Investimento Imobiliário De Responsabilidade Limitada", "tipo": "fii"},
    {"ticker": "TBOF11", "nome": "TB Office", "tipo": "fii"},
    {"ticker": "TCIN11", "nome": "Tourmalet V - Ed. Cidade Nova", "tipo": "fii"},
    {"ticker": "TCPF11", "nome": "Treecorp Real Estate Fdo Inv Imob - I", "tipo": "fii"},
    {"ticker": "TELD11", "nome": "Tellus Desenvolvimento Logístico", "tipo": "fii"},
    {"ticker": "TELF11", "nome": "Tellus Fundo De Fundos - Fii Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "TELM11", "nome": "Tellus Multiestratégia – Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "TEPP11", "nome": "Tellus Properties - Fdo Inv. Imob", "tipo": "fii"},
    {"ticker": "TFOF11", "nome": "Hedge TOP FOFII", "tipo": "fii"},
    {"ticker": "TGAR11", "nome": "TG Ativo Real", "tipo": "fii"},
    {"ticker": "THRA11", "nome": "Cyrela Thera Corporate", "tipo": "fii"},
    {"ticker": "TJKB11", "nome": "Tjk Renda Imobiliária Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "TMPS11", "nome": "Itaú Tempus Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "TOPP11", "nome": "Fii Topp", "tipo": "fii"},
    {"ticker": "TORD11", "nome": "Tordesilhas Ei Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "TOUR11", "nome": "Fdo Inv Imob Tourmalet Ii", "tipo": "fii"},
    {"ticker": "TRBL11", "nome": "Fdo De Invest Imob Tellus Rio Bravo Renda Logistic", "tipo": "fii"},
    {"ticker": "TRNT11", "nome": "Torre Norte", "tipo": "fii"},
    {"ticker": "TRPL11", "nome": "Terras Paulistas Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "TRUE11", "nome": "True Multiestratégia Fii", "tipo": "fii"},
    {"ticker": "TRXB11", "nome": "Trx Real Estate Ii Fdo. Invest. Imob.", "tipo": "fii"},
    {"ticker": "TRXF11", "nome": "TRX Real Estate", "tipo": "fii"},
    {"ticker": "TRXY11", "nome": "Fii Trxy", "tipo": "fii"},
    {"ticker": "TSER11", "nome": "Tishman Speyer Renda Corporativa", "tipo": "fii"},
    {"ticker": "TSNC11", "nome": "Transinc", "tipo": "fii"},
    {"ticker": "TSNM11", "nome": "Ts New Marginal", "tipo": "fii"},
    {"ticker": "TVRI11", "nome": "Tivio Renda Imobiliária Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "URHF11", "nome": "Urca Hedge Fund", "tipo": "fii"},
    {"ticker": "URPR11", "nome": "Urca Prime Renda", "tipo": "fii"},
    {"ticker": "VCHG11", "nome": "Vera Cruz CRI Residencial High Grade", "tipo": "fii"},
    {"ticker": "VCJR11", "nome": "Vectis Juros Real Fdo Inv. Imob. - Fii", "tipo": "fii"},
    {"ticker": "VCRI11", "nome": "Vinci Credit Securities Fundo De Investimento Imob", "tipo": "fii"},
    {"ticker": "VCRR11", "nome": "Vectis Renda Residencial", "tipo": "fii"},
    {"ticker": "VCTH11", "nome": "Vera Cruz Three Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "VDSV11", "nome": "Vic Desenvolvimento Vintage", "tipo": "fii"},
    {"ticker": "VERE11", "nome": "Vereda", "tipo": "fii"},
    {"ticker": "VGHF11", "nome": "Valora Hedge Fund", "tipo": "fii"},
    {"ticker": "VGII11", "nome": "Valora Cri Infra Ii Fii De Resp. Ltda", "tipo": "fii"},
    {"ticker": "VGIP11", "nome": "Valora Cri Índice De Preço", "tipo": "fii"},
    {"ticker": "VGIR11", "nome": "Valora Cri Cdi", "tipo": "fii"},
    {"ticker": "VGRI11", "nome": "Valora Renda Imob Fundo De Inves Imob -Resp Limit", "tipo": "fii"},
    {"ticker": "VIDS11", "nome": "Vic Desenvolvimento Vintage 20/21", "tipo": "fii"},
    {"ticker": "VIFI11", "nome": "Vinci Instrumentos Financeiros", "tipo": "fii"},
    {"ticker": "VILG11", "nome": "Vinci Logística Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "VINO11", "nome": "Vinci Offices Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "VISC11", "nome": "Vinci Shopping Centers", "tipo": "fii"},
    {"ticker": "VIUR11", "nome": "Vinci Imóveis Urbanos", "tipo": "fii"},
    {"ticker": "VJFD11", "nome": "Jfdcam Fundo De Investimento Imobiliário Fii", "tipo": "fii"},
    {"ticker": "VLIQ11", "nome": "Vinci Vifi 2 Fundo De Investimento Imobiliário Fii", "tipo": "fii"},
    {"ticker": "VLJS11", "nome": "Vector Queluz Lajes Corporativas", "tipo": "fii"},
    {"ticker": "VLOL11", "nome": "Vila Olímpia Corporate", "tipo": "fii"},
    {"ticker": "VOTS11", "nome": "Votorantim Securities Master", "tipo": "fii"},
    {"ticker": "VPPR11", "nome": "Xp Properties Fdo. Inv. Imob.", "tipo": "fii"},
    {"ticker": "VPSI11", "nome": "Polo Shopping Indaiatuba", "tipo": "fii"},
    {"ticker": "VRTA11", "nome": "Fator Verita", "tipo": "fii"},
    {"ticker": "VRTM11", "nome": "Fator Verità Multiestratégia Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "VSEC11", "nome": "Fdo Inv Imob Votorantim Securities", "tipo": "fii"},
    {"ticker": "VSHO11", "nome": "Fdo Inv Imob Votorantim Shopping", "tipo": "fii"},
    {"ticker": "VSLH11", "nome": "Versalhes Recebíveis Imobiliários", "tipo": "fii"},
    {"ticker": "VTBL11", "nome": "Fii Hieron Berlim", "tipo": "fii"},
    {"ticker": "VTLT11", "nome": "Votorantim Logística", "tipo": "fii"},
    {"ticker": "VTPA11", "nome": "Fdo. Invest. Imob. Votorantim Patrimonial V", "tipo": "fii"},
    {"ticker": "VTPL11", "nome": "Fdo Inv. Imob. Plus", "tipo": "fii"},
    {"ticker": "VTRT11", "nome": "Votorantim Securities Iii", "tipo": "fii"},
    {"ticker": "VTVI11", "nome": "Parking Partners Fdo. Invest. Imob.", "tipo": "fii"},
    {"ticker": "VTXI11", "nome": "Fdo. Invest. Imob. Votorantim Patrimonial Xii", "tipo": "fii"},
    {"ticker": "VVCO11", "nome": "V2 Edificios Corporativos Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "VVCR11", "nome": "BB Renda de Papeis Imobiliários II", "tipo": "fii"},
    {"ticker": "VVMR11", "nome": "Fdo.Invest. Imob. Multi Renda Urbana", "tipo": "fii"},
    {"ticker": "VVPR11", "nome": "Fdo Inv Imob - V2 Properties", "tipo": "fii"},
    {"ticker": "VVRI11", "nome": "V2 Renda Imobiliária Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "VXXV11", "nome": "Vx Xvi - Fdo Inv. Imob.", "tipo": "fii"},
    {"ticker": "WHGR11", "nome": "Whg Real Estate Fundo De Investimento Imobiliário", "tipo": "fii"},
    {"ticker": "WPLZ11", "nome": "Shopping West Plaza", "tipo": "fii"},
    {"ticker": "WSEC11", "nome": "Warren Securities Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "WTSP11", "nome": "Ourinvest RE I", "tipo": "fii"},
    {"ticker": "XBXO11", "nome": "R Cap 1810 Fundo De Fundos", "tipo": "fii"},
    {"ticker": "XLPR11", "nome": "Fii Xlpr Ri", "tipo": "fii"},
    {"ticker": "XPCI11", "nome": "Xp Credito Imobiliário - Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "XPCM11", "nome": "XP Corporate Macaé", "tipo": "fii"},
    {"ticker": "XPIN11", "nome": "XP Industrial", "tipo": "fii"},
    {"ticker": "XPLG11", "nome": "XP Log", "tipo": "fii"},
    {"ticker": "XPML11", "nome": "XP Malls", "tipo": "fii"},
    {"ticker": "XPRE11", "nome": "Fii Xpre", "tipo": "fii"},
    {"ticker": "XPSF11", "nome": "Xp Selection Fdo De Fundos Inv Imob - Fii", "tipo": "fii"},
    {"ticker": "YEES11", "nome": "Hedge Yees Habitações Econ Fdo De Inv Imob Resp L", "tipo": "fii"},
    {"ticker": "YUFI11", "nome": "Yuca Fdo Inv. Imob.", "tipo": "fii"},
    {"ticker": "ZAGH11", "nome": "Zagros Multiestratégia Fdo De Inv Imob", "tipo": "fii"},
    {"ticker": "ZAVC11", "nome": "Zavit Crédito Imobiliário – Fdo Inv Imob", "tipo": "fii"},
    {"ticker": "ZAVI11", "nome": "Zavit Real Estate Fund", "tipo": "fii"},
    {"ticker": "ZIFI11", "nome": "Zion Capital Fundo De Investimento Imobiliário", "tipo": "fii"},
]

ACOES = [
    {"ticker": "AALR3", "nome": "Alliança Saúde E Participações S.A.", "tipo": "acao"},
    {"ticker": "ABCB4", "nome": "Bco Abc Brasil S.A.", "tipo": "acao"},
    {"ticker": "ABEV3", "nome": "Ambev S.A.", "tipo": "acao"},
    {"ticker": "ADHM3", "nome": "Advanced Digital Health Medicina Preventiva S.A.", "tipo": "acao"},
    {"ticker": "AERI3", "nome": "Aeris Ind. E Com. De Equip. Geracao De Energia S.A", "tipo": "acao"},
    {"ticker": "AESB3", "nome": "Aes Brasil Energia S.A.", "tipo": "acao"},
    {"ticker": "AFLT3", "nome": "Afluente Transmissão De Energia Elétrica S/A", "tipo": "acao"},
    {"ticker": "AGRO3", "nome": "Brasilagro - Cia Bras De Prop Agricolas", "tipo": "acao"},
    {"ticker": "AGXY3", "nome": "Agrogalaxy Participações S.A.", "tipo": "acao"},
    {"ticker": "AHEB3", "nome": "Sao Paulo Turismo S.A.", "tipo": "acao"},
    {"ticker": "AHEB5", "nome": "Sao Paulo Turismo S.A.", "tipo": "acao"},
    {"ticker": "AHEB6", "nome": "Sao Paulo Turismo S.A.", "tipo": "acao"},
    {"ticker": "ALLD3", "nome": "Allied Tecnologia S.A.", "tipo": "acao"},
    {"ticker": "ALOS3", "nome": "Allos S.A", "tipo": "acao"},
    {"ticker": "ALPA3", "nome": "Alpargatas S.A.", "tipo": "acao"},
    {"ticker": "ALPA4", "nome": "Alpargatas S.A.", "tipo": "acao"},
    {"ticker": "ALPK3", "nome": "Allpark Empreendimentos Participacoes Servicos S.A", "tipo": "acao"},
    {"ticker": "ALUP11", "nome": "Alupar Investimento S/A", "tipo": "acao"},
    {"ticker": "ALUP3", "nome": "Alupar Investimento S/A", "tipo": "acao"},
    {"ticker": "ALUP4", "nome": "Alupar Investimento S/A", "tipo": "acao"},
    {"ticker": "AMAR3", "nome": "Marisa Lojas S.A.", "tipo": "acao"},
    {"ticker": "AMBP3", "nome": "Ambipar Participacoes E Empreendimentos S/A", "tipo": "acao"},
    {"ticker": "AMER3", "nome": "Americanas S.A", "tipo": "acao"},
    {"ticker": "AMOB3", "nome": "Automob Participações", "tipo": "acao"},
    {"ticker": "ANIM3", "nome": "Anima Holding S.A.", "tipo": "acao"},
    {"ticker": "APER3", "nome": "Alper Consultoria E Corretora De Seguros S.A.", "tipo": "acao"},
    {"ticker": "APTI3", "nome": "Siderurgica J. L. Aliperti S.A.", "tipo": "acao"},
    {"ticker": "APTI4", "nome": "Siderurgica J. L. Aliperti S.A.", "tipo": "acao"},
    {"ticker": "ARML3", "nome": "Armac Locação. Logística E Serviços S.A.", "tipo": "acao"},
    {"ticker": "ARND3", "nome": "ARANDU Investimentos S.A", "tipo": "acao"},
    {"ticker": "ASAI3", "nome": "Sendas Distribuidora S.A.", "tipo": "acao"},
    {"ticker": "AUAU3", "nome": "União Pet Participações S.A.", "tipo": "acao"},
    {"ticker": "AURE3", "nome": "Auren Energia S.A.", "tipo": "acao"},
    {"ticker": "AVLL3", "nome": "Alphaville S.A.", "tipo": "acao"},
    {"ticker": "AXIA3", "nome": "Centrais Elet Bras S.A. - Eletrobras", "tipo": "acao"},
    {"ticker": "AXIA5", "nome": "Centrais Elet Bras S.A. - Eletrobras", "tipo": "acao"},
    {"ticker": "AXIA6", "nome": "Centrais Elet Bras S.A. - Eletrobras", "tipo": "acao"},
    {"ticker": "AXIA7", "nome": "Centrais Elet Bras S.A. - Eletrobras", "tipo": "acao"},
    {"ticker": "AZEV3", "nome": "Azevedo E Travassos S.A.", "tipo": "acao"},
    {"ticker": "AZEV4", "nome": "Azevedo E Travassos S.A.", "tipo": "acao"},
    {"ticker": "AZTE3", "nome": "Azevedo & Travassos Energia S.A", "tipo": "acao"},
    {"ticker": "AZUL53", "nome": "Azul S.A.", "tipo": "acao"},
    {"ticker": "AZUL54", "nome": "Azul S.A.", "tipo": "acao"},
    {"ticker": "AZZA3", "nome": "Azzas 2154 S.A.", "tipo": "acao"},
    {"ticker": "B3SA3", "nome": "B3 S.A. - Brasil, Bolsa, Balcão", "tipo": "acao"},
    {"ticker": "BAHI3", "nome": "Bahema S.A.", "tipo": "acao"},
    {"ticker": "BALM3", "nome": "Baumer S.A.", "tipo": "acao"},
    {"ticker": "BALM4", "nome": "Baumer S.A.", "tipo": "acao"},
    {"ticker": "BAUH3", "nome": "Excelsior Alimentos S.A.", "tipo": "acao"},
    {"ticker": "BAUH4", "nome": "Excelsior Alimentos S.A.", "tipo": "acao"},
    {"ticker": "BAZA3", "nome": "Bco Amazonia S.A.", "tipo": "acao"},
    {"ticker": "BBAS3", "nome": "Bco Brasil S.A.", "tipo": "acao"},
    {"ticker": "BBDC3", "nome": "Bco Bradesco S.A.", "tipo": "acao"},
    {"ticker": "BBDC4", "nome": "Bco Bradesco S.A.", "tipo": "acao"},
    {"ticker": "BBML3", "nome": "Bbm Logistica S.A.", "tipo": "acao"},
    {"ticker": "BBSE3", "nome": "Bb Seguridade Participações S.A.", "tipo": "acao"},
    {"ticker": "BDLL3", "nome": "Bardella S.A. Industrias Mecanicas", "tipo": "acao"},
    {"ticker": "BDLL4", "nome": "Bardella S.A. Industrias Mecanicas", "tipo": "acao"},
    {"ticker": "BEEF3", "nome": "Minerva S.A.", "tipo": "acao"},
    {"ticker": "BEES3", "nome": "Banestes S.A. - Bco Est Espirito Santo", "tipo": "acao"},
    {"ticker": "BEES4", "nome": "Banestes S.A. - Bco Est Espirito Santo", "tipo": "acao"},
    {"ticker": "BFRE11", "nome": "Brazilian Finance E Real Estate S.A.", "tipo": "acao"},
    {"ticker": "BFRE12", "nome": "Brazilian Finance E Real Estate S.A.", "tipo": "acao"},
    {"ticker": "BGIP3", "nome": "Bco Estado De Sergipe S.A. - Banese", "tipo": "acao"},
    {"ticker": "BGIP4", "nome": "Bco Estado De Sergipe S.A. - Banese", "tipo": "acao"},
    {"ticker": "BHIA3", "nome": "Grupo Casas Bahia S.A.", "tipo": "acao"},
    {"ticker": "BIDI11", "nome": "Banco Inter S.A.", "tipo": "acao"},
    {"ticker": "BIDI3", "nome": "Banco Inter S.A.", "tipo": "acao"},
    {"ticker": "BIDI4", "nome": "Banco Inter S.A.", "tipo": "acao"},
    {"ticker": "BIOM3", "nome": "Biomm S.A.", "tipo": "acao"},
    {"ticker": "BLAU3", "nome": "Blau Farmacêutica S.A.", "tipo": "acao"},
    {"ticker": "BLUT3", "nome": "Blue Tech Solutions E.Q.I. S", "tipo": "acao"},
    {"ticker": "BLUT4", "nome": "Blue Tech Solutions E.Q.I. S", "tipo": "acao"},
    {"ticker": "BMEB3", "nome": "Bco Mercantil Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "BMEB4", "nome": "Bco Mercantil Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "BMGB4", "nome": "Banco Bmg S.A.", "tipo": "acao"},
    {"ticker": "BMIN3", "nome": "Bco Mercantil De Investimentos S.A.", "tipo": "acao"},
    {"ticker": "BMIN4", "nome": "Bco Mercantil De Investimentos S.A.", "tipo": "acao"},
    {"ticker": "BMKS3", "nome": "Bicicletas Monark S.A.", "tipo": "acao"},
    {"ticker": "BMOB3", "nome": "Bemobi Mobile Tech S.A.", "tipo": "acao"},
    {"ticker": "BNBR3", "nome": "Bco Nordeste Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "BOAS3", "nome": "Boa Vista Serviços S.A.", "tipo": "acao"},
    {"ticker": "BOBR3", "nome": "Bombril S.A.", "tipo": "acao"},
    {"ticker": "BOBR4", "nome": "Bombril S.A.", "tipo": "acao"},
    {"ticker": "BPAC11", "nome": "Bco Btg Pactual S.A.", "tipo": "acao"},
    {"ticker": "BPAC3", "nome": "Bco Btg Pactual S.A.", "tipo": "acao"},
    {"ticker": "BPAC5", "nome": "Bco Btg Pactual S.A.", "tipo": "acao"},
    {"ticker": "BPAN4", "nome": "Bco Pan S.A.", "tipo": "acao"},
    {"ticker": "BPAR3", "nome": "Bco Estado Do Para S.A.", "tipo": "acao"},
    {"ticker": "BPAT33", "nome": "Bco Patagonia S.A.", "tipo": "acao"},
    {"ticker": "BPHA3", "nome": "Brasil Pharma S.A.", "tipo": "acao"},
    {"ticker": "BRAP3", "nome": "Bradespar S.A.", "tipo": "acao"},
    {"ticker": "BRAP4", "nome": "Bradespar S.A.", "tipo": "acao"},
    {"ticker": "BRAV3", "nome": "Brava Energia Participações S.A.", "tipo": "acao"},
    {"ticker": "BRBI11", "nome": "Br Advisory Partners Participações S.A.", "tipo": "acao"},
    {"ticker": "BRBI3", "nome": "Br Advisory Partners Participações S.A.", "tipo": "acao"},
    {"ticker": "BRBI4", "nome": "Br Advisory Partners Participações S.A.", "tipo": "acao"},
    {"ticker": "BRFS3", "nome": "Brf S.A.", "tipo": "acao"},
    {"ticker": "BRGE11", "nome": "Consorcio Alfa De Administracao S.A.", "tipo": "acao"},
    {"ticker": "BRGE12", "nome": "Consorcio Alfa De Administracao S.A.", "tipo": "acao"},
    {"ticker": "BRGE3", "nome": "Consorcio Alfa De Administracao S.A.", "tipo": "acao"},
    {"ticker": "BRGE5", "nome": "Consorcio Alfa De Administracao S.A.", "tipo": "acao"},
    {"ticker": "BRGE6", "nome": "Consorcio Alfa De Administracao S.A.", "tipo": "acao"},
    {"ticker": "BRGE7", "nome": "Consorcio Alfa De Administracao S.A.", "tipo": "acao"},
    {"ticker": "BRGE8", "nome": "Consorcio Alfa De Administracao S.A.", "tipo": "acao"},
    {"ticker": "BRIV3", "nome": "Bco Alfa De Investimento S.A.", "tipo": "acao"},
    {"ticker": "BRIV4", "nome": "Bco Alfa De Investimento S.A.", "tipo": "acao"},
    {"ticker": "BRKM3", "nome": "Braskem S.A", "tipo": "acao"},
    {"ticker": "BRKM5", "nome": "Braskem S.A", "tipo": "acao"},
    {"ticker": "BRKM6", "nome": "Braskem S.A", "tipo": "acao"},
    {"ticker": "BRML3", "nome": "Br Malls Participacoes S.A.", "tipo": "acao"},
    {"ticker": "BRPR3", "nome": "Br Properties S.A.", "tipo": "acao"},
    {"ticker": "BRQB3", "nome": "Brq Solucoes Em Informatica S.A.", "tipo": "acao"},
    {"ticker": "BRSR3", "nome": "Bco Estado Do Rio Grande Do Sul S.A", "tipo": "acao"},
    {"ticker": "BRSR5", "nome": "Bco Estado Do Rio Grande Do Sul S.A", "tipo": "acao"},
    {"ticker": "BRSR6", "nome": "Bco Estado Do Rio Grande Do Sul S.A", "tipo": "acao"},
    {"ticker": "BRST3", "nome": "Brisanet Participações S.A.", "tipo": "acao"},
    {"ticker": "BSEV3", "nome": "Biosev S.A.", "tipo": "acao"},
    {"ticker": "BSLI3", "nome": "Brb Bco De Brasilia S.A.", "tipo": "acao"},
    {"ticker": "BSLI4", "nome": "Brb Bco De Brasilia S.A.", "tipo": "acao"},
    {"ticker": "BTTL4", "nome": "Embpar Participacoes S.A.", "tipo": "acao"},
    {"ticker": "CALI3", "nome": "Construtora Adolpho Lindenberg S.A.", "tipo": "acao"},
    {"ticker": "CALI4", "nome": "Construtora Adolpho Lindenberg S.A.", "tipo": "acao"},
    {"ticker": "CAMB3", "nome": "Cambuci S.A.", "tipo": "acao"},
    {"ticker": "CAMB4", "nome": "Cambuci S.A.", "tipo": "acao"},
    {"ticker": "CAML3", "nome": "Camil Alimentos S.A.", "tipo": "acao"},
    {"ticker": "CASH3", "nome": "Méliuz S.A.", "tipo": "acao"},
    {"ticker": "CASN3", "nome": "Cia Catarinense De Aguas E Saneam.-Casan", "tipo": "acao"},
    {"ticker": "CASN4", "nome": "Cia Catarinense De Aguas E Saneam.-Casan", "tipo": "acao"},
    {"ticker": "CATA3", "nome": "Cia Industrial Cataguases", "tipo": "acao"},
    {"ticker": "CATA4", "nome": "Cia Industrial Cataguases", "tipo": "acao"},
    {"ticker": "CBAV3", "nome": "Companhia Brasileira de Alumínio", "tipo": "acao"},
    {"ticker": "CBEE3", "nome": "Ampla Energia E Servicos S.A.", "tipo": "acao"},
    {"ticker": "CCXC3", "nome": "Ccx Carvão Da Colômbia S.A.", "tipo": "acao"},
    {"ticker": "CEAB3", "nome": "Cea Modas S.A.", "tipo": "acao"},
    {"ticker": "CEBR3", "nome": "Cia Energetica De Brasilia", "tipo": "acao"},
    {"ticker": "CEBR5", "nome": "Cia Energetica De Brasilia", "tipo": "acao"},
    {"ticker": "CEBR6", "nome": "Cia Energetica De Brasilia", "tipo": "acao"},
    {"ticker": "CEDO3", "nome": "Cia Fiacao Tecidos Cedro Cachoeira", "tipo": "acao"},
    {"ticker": "CEDO4", "nome": "Cia Fiacao Tecidos Cedro Cachoeira", "tipo": "acao"},
    {"ticker": "CEEB3", "nome": "Cia Eletricidade Est. Da Bahia - Coelba", "tipo": "acao"},
    {"ticker": "CEEB5", "nome": "Cia Eletricidade Est. Da Bahia - Coelba", "tipo": "acao"},
    {"ticker": "CEEB6", "nome": "Cia Eletricidade Est. Da Bahia - Coelba", "tipo": "acao"},
    {"ticker": "CEED3", "nome": "Cia Estadual De Distrib Ener Elet-Ceee-D", "tipo": "acao"},
    {"ticker": "CEED4", "nome": "Cia Estadual De Distrib Ener Elet-Ceee-D", "tipo": "acao"},
    {"ticker": "CEGR3", "nome": "Cia Distrib De Gas Do Rio De Janeiro-Ceg", "tipo": "acao"},
    {"ticker": "CEPE3", "nome": "Cia Energetica De Pernambuco - Celpe", "tipo": "acao"},
    {"ticker": "CEPE5", "nome": "Cia Energetica De Pernambuco - Celpe", "tipo": "acao"},
    {"ticker": "CEPE6", "nome": "Cia Energetica De Pernambuco - Celpe", "tipo": "acao"},
    {"ticker": "CESP3", "nome": "Cesp - Cia Energetica De Sao Paulo", "tipo": "acao"},
    {"ticker": "CESP5", "nome": "Cesp - Cia Energetica De Sao Paulo", "tipo": "acao"},
    {"ticker": "CESP6", "nome": "Cesp - Cia Energetica De Sao Paulo", "tipo": "acao"},
    {"ticker": "CGAS3", "nome": "Cia Gas De Sao Paulo - Comgas", "tipo": "acao"},
    {"ticker": "CGAS5", "nome": "Cia Gas De Sao Paulo - Comgas", "tipo": "acao"},
    {"ticker": "CGRA3", "nome": "Grazziotin S.A.", "tipo": "acao"},
    {"ticker": "CGRA4", "nome": "Grazziotin S.A.", "tipo": "acao"},
    {"ticker": "CIEL3", "nome": "Cielo S.A.", "tipo": "acao"},
    {"ticker": "CLSA3", "nome": "Clear Sale S.A.", "tipo": "acao"},
    {"ticker": "CLSC3", "nome": "Centrais Elet De Santa Catarina S.A.", "tipo": "acao"},
    {"ticker": "CLSC4", "nome": "Centrais Elet De Santa Catarina S.A.", "tipo": "acao"},
    {"ticker": "CMIG3", "nome": "Cia Energetica De Minas Gerais - Cemig", "tipo": "acao"},
    {"ticker": "CMIG4", "nome": "Cia Energetica De Minas Gerais - Cemig", "tipo": "acao"},
    {"ticker": "CMIN3", "nome": "Csn Mineração S.A.", "tipo": "acao"},
    {"ticker": "CMSA3", "nome": "Cims S.A.", "tipo": "acao"},
    {"ticker": "CMSA4", "nome": "Cims S.A.", "tipo": "acao"},
    {"ticker": "CNSY3", "nome": "Cinesystem S.A.", "tipo": "acao"},
    {"ticker": "COCE3", "nome": "Cia Energetica Do Ceara - Coelce", "tipo": "acao"},
    {"ticker": "COCE5", "nome": "Cia Energetica Do Ceara - Coelce", "tipo": "acao"},
    {"ticker": "COCE6", "nome": "Cia Energetica Do Ceara - Coelce", "tipo": "acao"},
    {"ticker": "COGN3", "nome": "Cogna Educação", "tipo": "acao"},
    {"ticker": "CORR3", "nome": "Correa Ribeiro S.A. Comercio E Industria", "tipo": "acao"},
    {"ticker": "CORR4", "nome": "Correa Ribeiro S.A. Comercio E Industria", "tipo": "acao"},
    {"ticker": "CPFE3", "nome": "Cpfl Energia S.A.", "tipo": "acao"},
    {"ticker": "CPLE3", "nome": "Cia Paranaense De Energia - Copel", "tipo": "acao"},
    {"ticker": "CPLE5", "nome": "Cia Paranaense De Energia - Copel", "tipo": "acao"},
    {"ticker": "CPLE6", "nome": "Cia Paranaense De Energia - Copel", "tipo": "acao"},
    {"ticker": "CPRE3", "nome": "Cpfl Energias Renováveis S.A.", "tipo": "acao"},
    {"ticker": "CREM3", "nome": "Cremer S.A.", "tipo": "acao"},
    {"ticker": "CRFB3", "nome": "Atacadão S.A.", "tipo": "acao"},
    {"ticker": "CRIV3", "nome": "Financeira Alfa S.A.- Cred Financ E Invs", "tipo": "acao"},
    {"ticker": "CRIV4", "nome": "Financeira Alfa S.A.- Cred Financ E Invs", "tipo": "acao"},
    {"ticker": "CRPG3", "nome": "Tronox Pigmentos Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "CRPG5", "nome": "Tronox Pigmentos Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "CRPG6", "nome": "Tronox Pigmentos Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "CSAB3", "nome": "Cia Seguros Alianca Da Bahia", "tipo": "acao"},
    {"ticker": "CSAB4", "nome": "Cia Seguros Alianca Da Bahia", "tipo": "acao"},
    {"ticker": "CSAN3", "nome": "Cosan S.A.", "tipo": "acao"},
    {"ticker": "CSED3", "nome": "Cruzeiro Do Sul Educacional S.A.", "tipo": "acao"},
    {"ticker": "CSMG3", "nome": "Cia Saneamento De Minas Gerais-Copasa Mg", "tipo": "acao"},
    {"ticker": "CSNA3", "nome": "Cia Siderurgica Nacional", "tipo": "acao"},
    {"ticker": "CSRN3", "nome": "Cia Energetica Do Rio Gde Norte - Cosern", "tipo": "acao"},
    {"ticker": "CSRN5", "nome": "Cia Energetica Do Rio Gde Norte - Cosern", "tipo": "acao"},
    {"ticker": "CSRN6", "nome": "Cia Energetica Do Rio Gde Norte - Cosern", "tipo": "acao"},
    {"ticker": "CSUD3", "nome": "Csu Digital S.A.", "tipo": "acao"},
    {"ticker": "CTAX3", "nome": "Contax Participações S.A.", "tipo": "acao"},
    {"ticker": "CTCA3", "nome": "Ctc - Centro De Tecnologia Canavieira S.A.", "tipo": "acao"},
    {"ticker": "CTKA3", "nome": "Karsten S.A.", "tipo": "acao"},
    {"ticker": "CTKA4", "nome": "Karsten S.A.", "tipo": "acao"},
    {"ticker": "CTNM3", "nome": "Cia Tecidos Norte De Minas Coteminas", "tipo": "acao"},
    {"ticker": "CTNM4", "nome": "Cia Tecidos Norte De Minas Coteminas", "tipo": "acao"},
    {"ticker": "CTSA3", "nome": "Cia Tecidos Santanense", "tipo": "acao"},
    {"ticker": "CTSA4", "nome": "Cia Tecidos Santanense", "tipo": "acao"},
    {"ticker": "CTSA8", "nome": "Cia Tecidos Santanense", "tipo": "acao"},
    {"ticker": "CURY3", "nome": "Cury Construtora E Incorporadora S.A.", "tipo": "acao"},
    {"ticker": "CVCB3", "nome": "Cvc Brasil Operadora E Agência De Viagens S.A.", "tipo": "acao"},
    {"ticker": "CXSE3", "nome": "Caixa Seguridade Participações S.A.", "tipo": "acao"},
    {"ticker": "CYRE3", "nome": "Cyrela Brazil Realty S.A.Empreend E Part", "tipo": "acao"},
    {"ticker": "CYRE4", "nome": "Cyrela Brazil Realty S.A.Empreend E Part", "tipo": "acao"},
    {"ticker": "DASA3", "nome": "Diagnosticos Da America S.A.", "tipo": "acao"},
    {"ticker": "DESK3", "nome": "Desktop - Sigmanet Comunicação Multimídia S.A.", "tipo": "acao"},
    {"ticker": "DEXP3", "nome": "Dexxos Participacoes S.A.", "tipo": "acao"},
    {"ticker": "DEXP4", "nome": "Dexxos Participacoes S.A.", "tipo": "acao"},
    {"ticker": "DIRR3", "nome": "Direcional Engenharia S.A.", "tipo": "acao"},
    {"ticker": "DMMO3", "nome": "Dommo Energia S.A.", "tipo": "acao"},
    {"ticker": "DMVF3", "nome": "D1000 Varejo Farma Participações S.A.", "tipo": "acao"},
    {"ticker": "DOHL3", "nome": "Dohler S.A.", "tipo": "acao"},
    {"ticker": "DOHL4", "nome": "Dohler S.A.", "tipo": "acao"},
    {"ticker": "DOTZ3", "nome": "Dotz S.A.", "tipo": "acao"},
    {"ticker": "DTCY3", "nome": "Dtcom - Direct To Company S.A.", "tipo": "acao"},
    {"ticker": "DTCY4", "nome": "Dtcom - Direct To Company S.A.", "tipo": "acao"},
    {"ticker": "DXCO3", "nome": "Duratex S.A.", "tipo": "acao"},
    {"ticker": "EALT3", "nome": "Electro Aco Altona S.A.", "tipo": "acao"},
    {"ticker": "EALT4", "nome": "Electro Aco Altona S.A.", "tipo": "acao"},
    {"ticker": "ECOR3", "nome": "Ecorodovias Infraestrutura E Logística S.A.", "tipo": "acao"},
    {"ticker": "ECPR3", "nome": "Empresa Nac Com Redito Part S.A.Encorpar", "tipo": "acao"},
    {"ticker": "ECPR4", "nome": "Empresa Nac Com Redito Part S.A.Encorpar", "tipo": "acao"},
    {"ticker": "EEEL3", "nome": "Cia Estadual Ger.Trans.Ener.Elet-Ceee-Gt", "tipo": "acao"},
    {"ticker": "EEEL4", "nome": "Cia Estadual Ger.Trans.Ener.Elet-Ceee-Gt", "tipo": "acao"},
    {"ticker": "EGIE3", "nome": "Engie Brasil Energia S.A.", "tipo": "acao"},
    {"ticker": "EKTR3", "nome": "Elektro Redes S.A.", "tipo": "acao"},
    {"ticker": "EKTR4", "nome": "Elektro Redes S.A.", "tipo": "acao"},
    {"ticker": "ELEK3", "nome": "Elekeiroz S.A.", "tipo": "acao"},
    {"ticker": "ELEK4", "nome": "Elekeiroz S.A.", "tipo": "acao"},
    {"ticker": "ELMD3", "nome": "Eletromidia S.A.", "tipo": "acao"},
    {"ticker": "ELPL3", "nome": "Eletropaulo Metrop. Elet. Sao Paulo S.A.", "tipo": "acao"},
    {"ticker": "EMAE3", "nome": "Emae - Empresa Metrop.Aguas Energia S.A.", "tipo": "acao"},
    {"ticker": "EMAE4", "nome": "Emae - Empresa Metrop.Aguas Energia S.A.", "tipo": "acao"},
    {"ticker": "EMBJ3", "nome": "Embraer S.A.", "tipo": "acao"},
    {"ticker": "ENAT3", "nome": "Enauta Participações S.A.", "tipo": "acao"},
    {"ticker": "ENBR3", "nome": "Edp - Energias Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "ENEV3", "nome": "Eneva S.A", "tipo": "acao"},
    {"ticker": "ENGI11", "nome": "Energisa S.A.", "tipo": "acao"},
    {"ticker": "ENGI3", "nome": "Energisa S.A.", "tipo": "acao"},
    {"ticker": "ENGI4", "nome": "Energisa S.A.", "tipo": "acao"},
    {"ticker": "ENJU3", "nome": "Enjoei.Com.Br Atividades De Internet S.A.", "tipo": "acao"},
    {"ticker": "ENMT3", "nome": "Energisa Mato Grosso-Distribuidora De Energia S/A", "tipo": "acao"},
    {"ticker": "ENMT4", "nome": "Energisa Mato Grosso-Distribuidora De Energia S/A", "tipo": "acao"},
    {"ticker": "EPAR3", "nome": "Embpar Participacoes S.A.", "tipo": "acao"},
    {"ticker": "EQPA3", "nome": "Equatorial Para Distribuidora De Energia S.A.", "tipo": "acao"},
    {"ticker": "EQPA5", "nome": "Equatorial Para Distribuidora De Energia S.A.", "tipo": "acao"},
    {"ticker": "EQPA6", "nome": "Equatorial Para Distribuidora De Energia S.A.", "tipo": "acao"},
    {"ticker": "EQPA7", "nome": "Equatorial Para Distribuidora De Energia S.A.", "tipo": "acao"},
    {"ticker": "EQTL3", "nome": "Equatorial Energia S.A.", "tipo": "acao"},
    {"ticker": "ESPA3", "nome": "Mpm Corpóreos S.A.", "tipo": "acao"},
    {"ticker": "ESTR3", "nome": "Manufatura De Brinquedos Estrela S.A.", "tipo": "acao"},
    {"ticker": "ESTR4", "nome": "Manufatura De Brinquedos Estrela S.A.", "tipo": "acao"},
    {"ticker": "ETER3", "nome": "Eternit S.A.", "tipo": "acao"},
    {"ticker": "EUCA3", "nome": "Eucatex S.A. Industria E Comercio", "tipo": "acao"},
    {"ticker": "EUCA4", "nome": "Eucatex S.A. Industria E Comercio", "tipo": "acao"},
    {"ticker": "EVEN3", "nome": "Even Construtora E Incorporadora S.A.", "tipo": "acao"},
    {"ticker": "EZTC3", "nome": "Ez Tec Empreend. E Participacoes S.A.", "tipo": "acao"},
    {"ticker": "FBMC3", "nome": "Fibam Companhia Industrial", "tipo": "acao"},
    {"ticker": "FBMC4", "nome": "Fibam Companhia Industrial", "tipo": "acao"},
    {"ticker": "FESA3", "nome": "Cia Ferro Ligas Da Bahia - Ferbasa", "tipo": "acao"},
    {"ticker": "FESA4", "nome": "Cia Ferro Ligas Da Bahia - Ferbasa", "tipo": "acao"},
    {"ticker": "FHER3", "nome": "Fertilizantes Heringer S.A.", "tipo": "acao"},
    {"ticker": "FICT3", "nome": "Fictor Alimentos SA", "tipo": "acao"},
    {"ticker": "FIEI3", "nome": "Fica Empreendimentos Imobiliários S.A", "tipo": "acao"},
    {"ticker": "FIGE3", "nome": "Investimentos Bemge S.A.", "tipo": "acao"},
    {"ticker": "FIGE4", "nome": "Investimentos Bemge S.A.", "tipo": "acao"},
    {"ticker": "FIQE3", "nome": "Unifique Telecomunicações S.A.", "tipo": "acao"},
    {"ticker": "FLEX3", "nome": "Flex Gestão De Relacionamentos S.A.", "tipo": "acao"},
    {"ticker": "FLRY3", "nome": "Fleury S.A.", "tipo": "acao"},
    {"ticker": "FNCN3", "nome": "Finansinos S.A.- Credito Financ E Invest", "tipo": "acao"},
    {"ticker": "FRAS3", "nome": "Frasle Mobility S.A.", "tipo": "acao"},
    {"ticker": "FRIO3", "nome": "Metalfrio Solutions S.A.", "tipo": "acao"},
    {"ticker": "FRTA3", "nome": "Pomifrutas S/A", "tipo": "acao"},
    {"ticker": "G2DI33", "nome": "G2D Investments Ltd", "tipo": "acao"},
    {"ticker": "GBIO33", "nome": "Biotoscana Investments S.A.", "tipo": "acao"},
    {"ticker": "GEPA3", "nome": "Rio Paranapanema Energia S.A.", "tipo": "acao"},
    {"ticker": "GEPA4", "nome": "Rio Paranapanema Energia S.A.", "tipo": "acao"},
    {"ticker": "GETT11", "nome": "Getnet Adquirencia E Serv Para Meios De Pgto S.A.", "tipo": "acao"},
    {"ticker": "GETT3", "nome": "Getnet Adquirencia E Serv Para Meios De Pgto S.A.", "tipo": "acao"},
    {"ticker": "GETT4", "nome": "Getnet Adquirencia E Serv Para Meios De Pgto S.A.", "tipo": "acao"},
    {"ticker": "GFSA3", "nome": "Gafisa S.A.", "tipo": "acao"},
    {"ticker": "GGBR3", "nome": "Gerdau S.A.", "tipo": "acao"},
    {"ticker": "GGBR4", "nome": "Gerdau S.A.", "tipo": "acao"},
    {"ticker": "GGPS3", "nome": "Gps Participacoes E Empreendimentos S.A.", "tipo": "acao"},
    {"ticker": "GMAT3", "nome": "Grupo Mateus S.A.", "tipo": "acao"},
    {"ticker": "GNDI3", "nome": "Notre Dame Intermedica Participacoes Sa", "tipo": "acao"},
    {"ticker": "GOAU3", "nome": "Metalurgica Gerdau S.A.", "tipo": "acao"},
    {"ticker": "GOAU4", "nome": "Metalurgica Gerdau S.A.", "tipo": "acao"},
    {"ticker": "GOLL54", "nome": "Gol Linhas Aereas Inteligentes S.A.", "tipo": "acao"},
    {"ticker": "GPAR3", "nome": "Cia Celg De Participacoes - Celgpar", "tipo": "acao"},
    {"ticker": "GPIV33", "nome": "Gp Investments, Ltd.", "tipo": "acao"},
    {"ticker": "GRAO3", "nome": "Humberg Agribrasil Com. E Export. De Grãos S.A.", "tipo": "acao"},
    {"ticker": "GRND3", "nome": "Grendene S.A.", "tipo": "acao"},
    {"ticker": "GSHP3", "nome": "General Shopping E Outlets Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "HAGA3", "nome": "Haga S.A. Industria E Comercio", "tipo": "acao"},
    {"ticker": "HAGA4", "nome": "Haga S.A. Industria E Comercio", "tipo": "acao"},
    {"ticker": "HAPV3", "nome": "Hapvida Participacoes E Investimentos Sa", "tipo": "acao"},
    {"ticker": "HBOR3", "nome": "Helbor Empreendimentos S.A.", "tipo": "acao"},
    {"ticker": "HBRE3", "nome": "Hbr Realty Empreendimentos Imobiliarios S/A", "tipo": "acao"},
    {"ticker": "HBSA3", "nome": "Hidrovias Do Brasil S.A.", "tipo": "acao"},
    {"ticker": "HBTS3", "nome": "Cia Habitasul De Participacoes", "tipo": "acao"},
    {"ticker": "HBTS5", "nome": "Cia Habitasul De Participacoes", "tipo": "acao"},
    {"ticker": "HBTS6", "nome": "Cia Habitasul De Participacoes", "tipo": "acao"},
    {"ticker": "HETA3", "nome": "Hercules S.A. Fabrica De Talheres", "tipo": "acao"},
    {"ticker": "HETA4", "nome": "Hercules S.A. Fabrica De Talheres", "tipo": "acao"},
    {"ticker": "HGTX3", "nome": "Cia Hering", "tipo": "acao"},
    {"ticker": "HOOT3", "nome": "Hoteis Othon S.A.", "tipo": "acao"},
    {"ticker": "HOOT4", "nome": "Hoteis Othon S.A.", "tipo": "acao"},
    {"ticker": "HYPE3", "nome": "Hypera S.A.", "tipo": "acao"},
    {"ticker": "IDVL3", "nome": "Bco Indusval S.A.", "tipo": "acao"},
    {"ticker": "IDVL4", "nome": "Bco Indusval S.A.", "tipo": "acao"},
    {"ticker": "IFCM3", "nome": "Infracommerce Cxaas S.A.", "tipo": "acao"},
    {"ticker": "IGBR3", "nome": "Igb Eletrônica S/A", "tipo": "acao"},
    {"ticker": "IGSN3", "nome": "Igua Saneamento S.A.", "tipo": "acao"},
    {"ticker": "IGTA3", "nome": "Iguatemi Empresa De Shopping Centers S.A", "tipo": "acao"},
    {"ticker": "IGTI11", "nome": "Jereissati Participacoes S.A.", "tipo": "acao"},
    {"ticker": "IGTI3", "nome": "Jereissati Participacoes S.A.", "tipo": "acao"},
    {"ticker": "IGTI4", "nome": "Jereissati Participacoes S.A.", "tipo": "acao"},
    {"ticker": "INEP3", "nome": "Inepar S.A. Industria E Construcoes", "tipo": "acao"},
    {"ticker": "INEP4", "nome": "Inepar S.A. Industria E Construcoes", "tipo": "acao"},
    {"ticker": "INNT3", "nome": "Inter Construtora E Incorporadora S.A.", "tipo": "acao"},
    {"ticker": "INTB3", "nome": "Intelbras S.A. Ind De Telec Eletronica Brasileira", "tipo": "acao"},
    {"ticker": "IRBR3", "nome": "Irb - Brasil Resseguros S.A.", "tipo": "acao"},
    {"ticker": "ISAE3", "nome": "Isa Energia Brasil S.A", "tipo": "acao"},
    {"ticker": "ISAE4", "nome": "Isa Energia Brasil S.A", "tipo": "acao"},
    {"ticker": "ITEC3", "nome": "Itautec S.A. - Grupo Itautec", "tipo": "acao"},
    {"ticker": "ITSA3", "nome": "Itausa Investimentos Itau S.A.", "tipo": "acao"},
    {"ticker": "ITSA4", "nome": "Itausa Investimentos Itau S.A.", "tipo": "acao"},
    {"ticker": "ITUB3", "nome": "Itau Unibanco Holding S.A.", "tipo": "acao"},
    {"ticker": "ITUB4", "nome": "Itau Unibanco Holding S.A.", "tipo": "acao"},
    {"ticker": "JALL3", "nome": "Jalles Machado S.A.", "tipo": "acao"},
    {"ticker": "JBSS3", "nome": "Jbs S.A.", "tipo": "acao"},
    {"ticker": "JFEN3", "nome": "Joao Fortes Engenharia S.A.", "tipo": "acao"},
    {"ticker": "JHSF3", "nome": "Jhsf Participacoes S.A.", "tipo": "acao"},
    {"ticker": "JOPA3", "nome": "Josapar-Joaquim Oliveira S.A. - Particip", "tipo": "acao"},
    {"ticker": "JOPA4", "nome": "Josapar-Joaquim Oliveira S.A. - Particip", "tipo": "acao"},
    {"ticker": "JSLG3", "nome": "Jsl S.A.", "tipo": "acao"},
    {"ticker": "KEPL3", "nome": "Kepler Weber S.A.", "tipo": "acao"},
    {"ticker": "KLBN11", "nome": "Klabin S.A.", "tipo": "acao"},
    {"ticker": "KLBN3", "nome": "Klabin S.A.", "tipo": "acao"},
    {"ticker": "KLBN4", "nome": "Klabin S.A.", "tipo": "acao"},
    {"ticker": "KRSA3", "nome": "Kora Saúde Participações S.A", "tipo": "acao"},
    {"ticker": "LAME3", "nome": "Lojas Americanas S.A.", "tipo": "acao"},
    {"ticker": "LAME4", "nome": "Lojas Americanas S.A.", "tipo": "acao"},
    {"ticker": "LAND3", "nome": "Terra Santa Propriedades Agricolas S.A.", "tipo": "acao"},
    {"ticker": "LAVV3", "nome": "Lavvi Empreendimentos Imobiliários S.A.", "tipo": "acao"},
    {"ticker": "LCAM3", "nome": "Cia Locação Das Américas", "tipo": "acao"},
    {"ticker": "LEVE3", "nome": "Mahle-Metal Leve S.A.", "tipo": "acao"},
    {"ticker": "LHER3", "nome": "Lojas Hering S.A.", "tipo": "acao"},
    {"ticker": "LHER4", "nome": "Lojas Hering S.A.", "tipo": "acao"},
    {"ticker": "LIGT3", "nome": "Light S.A.", "tipo": "acao"},
    {"ticker": "LINX3", "nome": "Linx S.A.", "tipo": "acao"},
    {"ticker": "LIPR3", "nome": "Eletrobrás Participações S.A. - Eletropar", "tipo": "acao"},
    {"ticker": "LJQQ3", "nome": "Lojas Quero-Quero S/A", "tipo": "acao"},
    {"ticker": "LOGG3", "nome": "Log Commercial Properties", "tipo": "acao"},
    {"ticker": "LOGN3", "nome": "Log-In Logistica Intermodal S.A.", "tipo": "acao"},
    {"ticker": "LPSB3", "nome": "Lps Brasil - Consultoria De Imoveis S.A.", "tipo": "acao"},
    {"ticker": "LREN3", "nome": "Lojas Renner S.A.", "tipo": "acao"},
    {"ticker": "LUPA3", "nome": "Lupatech S.A.", "tipo": "acao"},
    {"ticker": "LUXM3", "nome": "Trevisa Investimentos S.A.", "tipo": "acao"},
    {"ticker": "LUXM4", "nome": "Trevisa Investimentos S.A.", "tipo": "acao"},
    {"ticker": "LWSA3", "nome": "Locaweb Serviços De Internet S.A.", "tipo": "acao"},
    {"ticker": "MAPT3", "nome": "Cemepe Investimentos S.A.", "tipo": "acao"},
    {"ticker": "MAPT4", "nome": "Cemepe Investimentos S.A.", "tipo": "acao"},
    {"ticker": "MATD3", "nome": "Hospital Mater Dei Sa", "tipo": "acao"},
    {"ticker": "MBRF3", "nome": "MBRF Global Foods Company S.A.", "tipo": "acao"},
    {"ticker": "MDIA3", "nome": "M.Dias Branco S.A. Ind Com De Alimentos", "tipo": "acao"},
    {"ticker": "MDNE3", "nome": "Moura Dubeux Engenharia S/A", "tipo": "acao"},
    {"ticker": "MEAL3", "nome": "International Meal Company Alimentacao S.A.", "tipo": "acao"},
    {"ticker": "MELK3", "nome": "Melnick Even Desenvolvimento Imobiliário S.A.", "tipo": "acao"},
    {"ticker": "MERC3", "nome": "Mercantil Brasil Financ S.A. C.F.I.", "tipo": "acao"},
    {"ticker": "MERC4", "nome": "Mercantil Brasil Financ S.A. C.F.I.", "tipo": "acao"},
    {"ticker": "MGEL3", "nome": "Mangels Industrial S.A.", "tipo": "acao"},
    {"ticker": "MGEL4", "nome": "Mangels Industrial S.A.", "tipo": "acao"},
    {"ticker": "MGLU3", "nome": "Magazine Luiza S.A.", "tipo": "acao"},
    {"ticker": "MILS3", "nome": "Mills Estruturas E Serviços De Engenharia S.A.", "tipo": "acao"},
    {"ticker": "MLAS3", "nome": "Multilaser Industrial S.A.", "tipo": "acao"},
    {"ticker": "MMXM3", "nome": "Mmx Mineracao E Metalicos S.A.", "tipo": "acao"},
    {"ticker": "MNDL3", "nome": "Mundial S.A. - Produtos De Consumo", "tipo": "acao"},
    {"ticker": "MNPR3", "nome": "Minupar Participacoes S.A.", "tipo": "acao"},
    {"ticker": "MOAR3", "nome": "Monteiro Aranha S.A.", "tipo": "acao"},
    {"ticker": "MODL11", "nome": "Banco Modal S.A", "tipo": "acao"},
    {"ticker": "MODL3", "nome": "Banco Modal S.A", "tipo": "acao"},
    {"ticker": "MODL4", "nome": "Banco Modal S.A", "tipo": "acao"},
    {"ticker": "MOSI3", "nome": "Mosaico Tecnologia ao Consumidor S.A.", "tipo": "acao"},
    {"ticker": "MOTV3", "nome": "Motiva Infraestrutura De Mobilidade S.A.", "tipo": "acao"},
    {"ticker": "MOVI3", "nome": "Movida Participacoes Sa", "tipo": "acao"},
    {"ticker": "MRVE3", "nome": "Mrv Engenharia E Participacoes S.A.", "tipo": "acao"},
    {"ticker": "MSPA3", "nome": "Cia Melhoramentos De Sao Paulo", "tipo": "acao"},
    {"ticker": "MSPA4", "nome": "Cia Melhoramentos De Sao Paulo", "tipo": "acao"},
    {"ticker": "MSRO3", "nome": "Maestro Locadora De Veiculos S.A.", "tipo": "acao"},
    {"ticker": "MTIG3", "nome": "Metalgrafica Iguacu S.A.", "tipo": "acao"},
    {"ticker": "MTIG4", "nome": "Metalgrafica Iguacu S.A.", "tipo": "acao"},
    {"ticker": "MTRE3", "nome": "Mitre Realty Empreendimentos E Participações S.A.", "tipo": "acao"},
    {"ticker": "MTSA3", "nome": "Metisa Metalurgica Timboense S.A.", "tipo": "acao"},
    {"ticker": "MTSA4", "nome": "Metisa Metalurgica Timboense S.A.", "tipo": "acao"},
    {"ticker": "MULT3", "nome": "Multiplan - Empreend Imobiliarios S.A.", "tipo": "acao"},
    {"ticker": "MWET3", "nome": "Wetzel S.A.", "tipo": "acao"},
    {"ticker": "MWET4", "nome": "Wetzel S.A.", "tipo": "acao"},
    {"ticker": "MYPK3", "nome": "Iochpe Maxion S.A.", "tipo": "acao"},
    {"ticker": "NAFG3", "nome": "Nadir Figueiredo Ind E Com S.A.", "tipo": "acao"},
    {"ticker": "NAFG4", "nome": "Nadir Figueiredo Ind E Com S.A.", "tipo": "acao"},
    {"ticker": "NATU3", "nome": "Natura Cosmeticos S.A.", "tipo": "acao"},
    {"ticker": "NEMO3", "nome": "Suzano Holding S.A.", "tipo": "acao"},
    {"ticker": "NEMO4", "nome": "Suzano Holding S.A.", "tipo": "acao"},
    {"ticker": "NEMO5", "nome": "Suzano Holding S.A.", "tipo": "acao"},
    {"ticker": "NEMO6", "nome": "Suzano Holding S.A.", "tipo": "acao"},
    {"ticker": "NEOE3", "nome": "Neoenergia S.A.", "tipo": "acao"},
    {"ticker": "NEXP3", "nome": "Nexpe Participações S.A", "tipo": "acao"},
    {"ticker": "NGRD3", "nome": "Neogrid Participacoes S.A.", "tipo": "acao"},
    {"ticker": "NORD3", "nome": "Nordon Industrias Metalurgicas S.A.", "tipo": "acao"},
    {"ticker": "NRTQ3", "nome": "Nortec Química S.A.", "tipo": "acao"},
    {"ticker": "NTCO3", "nome": "Natura &Co Holding S.A.", "tipo": "acao"},
    {"ticker": "NUTR3", "nome": "Nutriplant Industria E Comercio S.A.", "tipo": "acao"},
    {"ticker": "OBTC3", "nome": "Oranjebtc S.A. - Educação E Investimento", "tipo": "acao"},
    {"ticker": "ODER3", "nome": "Conservas Oderich S.A.", "tipo": "acao"},
    {"ticker": "ODER4", "nome": "Conservas Oderich S.A.", "tipo": "acao"},
    {"ticker": "OFSA3", "nome": "Ouro Fino Saude Animal Participacoes S.A.", "tipo": "acao"},
    {"ticker": "OGXP3", "nome": "Óleo E Gás Participações S.A.", "tipo": "acao"},
    {"ticker": "OIBR3", "nome": "Oi S.A.", "tipo": "acao"},
    {"ticker": "OIBR4", "nome": "Oi S.A.", "tipo": "acao"},
    {"ticker": "OMGE3", "nome": "Omega Geração S.A.", "tipo": "acao"},
    {"ticker": "ONCO3", "nome": "Oncoclinicas Do Brasil Servicos Medicos S.A.", "tipo": "acao"},
    {"ticker": "OPCT3", "nome": "Oceanpact Servicos Maritimos S.A.", "tipo": "acao"},
    {"ticker": "ORVR3", "nome": "Orizon Valorizacao De Residuos S.A.", "tipo": "acao"},
    {"ticker": "OSXB3", "nome": "Osx Brasil S.A.", "tipo": "acao"},
    {"ticker": "PARD3", "nome": "Instituto Hermes Pardini S.A.", "tipo": "acao"},
    {"ticker": "PASS3", "nome": "Compass Gas E Energia S.A", "tipo": "acao"},
    {"ticker": "PATI3", "nome": "Panatlantica S.A.", "tipo": "acao"},
    {"ticker": "PATI4", "nome": "Panatlantica S.A.", "tipo": "acao"},
    {"ticker": "PCAR3", "nome": "Cia Brasileira De Distribuicao", "tipo": "acao"},
    {"ticker": "PCAR4", "nome": "Cia Brasileira De Distribuicao", "tipo": "acao"},
    {"ticker": "PDGR3", "nome": "Pdg Realty S.A. Empreend E Participacoes", "tipo": "acao"},
    {"ticker": "PDTC3", "nome": "Padtec Holding S.A.", "tipo": "acao"},
    {"ticker": "PEAB3", "nome": "Cia Participacoes Alianca Da Bahia", "tipo": "acao"},
    {"ticker": "PEAB4", "nome": "Cia Participacoes Alianca Da Bahia", "tipo": "acao"},
    {"ticker": "PETR3", "nome": "Petroleo Brasileiro S.A. Petrobras", "tipo": "acao"},
    {"ticker": "PETR4", "nome": "Petroleo Brasileiro S.A. Petrobras", "tipo": "acao"},
    {"ticker": "PETZ3", "nome": "Pet Center Comercio E Participacoes S.A.", "tipo": "acao"},
    {"ticker": "PFRM3", "nome": "Profarma Distrib Prod Farmaceuticos S.A.", "tipo": "acao"},
    {"ticker": "PGMN3", "nome": "Empreendimentos Pague Menos S.A.", "tipo": "acao"},
    {"ticker": "PINE14", "nome": "Bco Pine S.A.", "tipo": "acao"},
    {"ticker": "PINE3", "nome": "Bco Pine S.A.", "tipo": "acao"},
    {"ticker": "PINE4", "nome": "Bco Pine S.A.", "tipo": "acao"},
    {"ticker": "PLAS3", "nome": "Plascar Participacoes Industriais S.A.", "tipo": "acao"},
    {"ticker": "PLPL3", "nome": "Plano & Plano Desenvolvimento Imobiliário S.A.", "tipo": "acao"},
    {"ticker": "PMAM3", "nome": "Paranapanema S.A.", "tipo": "acao"},
    {"ticker": "PNVL3", "nome": "Dimed S.A. Distribuidora De Medicamentos", "tipo": "acao"},
    {"ticker": "PNVL4", "nome": "Dimed S.A. Distribuidora De Medicamentos", "tipo": "acao"},
    {"ticker": "POMO3", "nome": "Marcopolo S.A.", "tipo": "acao"},
    {"ticker": "POMO4", "nome": "Marcopolo S.A.", "tipo": "acao"},
    {"ticker": "PORT3", "nome": "Wilson Sons Holdings Brasil S.A.", "tipo": "acao"},
    {"ticker": "POSI3", "nome": "Positivo Tecnologia S.A.", "tipo": "acao"},
    {"ticker": "POWE3", "nome": "Focus Energia Holding Participações S.A", "tipo": "acao"},
    {"ticker": "PPAR3", "nome": "Polpar S.A.", "tipo": "acao"},
    {"ticker": "PPAR4", "nome": "Polpar S.A.", "tipo": "acao"},
    {"ticker": "PPLA11", "nome": "Ppla Participations Ltd.", "tipo": "acao"},
    {"ticker": "PRIO3", "nome": "Petro Rio S.A.", "tipo": "acao"},
    {"ticker": "PRNR3", "nome": "Priner Serviços Industriais S.A.", "tipo": "acao"},
    {"ticker": "PSSA3", "nome": "Porto Seguro S.A.", "tipo": "acao"},
    {"ticker": "PTBL3", "nome": "Pbg S/A", "tipo": "acao"},
    {"ticker": "PTCA11", "nome": "Pratica Klimaquip Industria E Comercio Sa", "tipo": "acao"},
    {"ticker": "PTCA3", "nome": "Pratica Klimaquip Industria E Comercio Sa", "tipo": "acao"},
    {"ticker": "PTNT3", "nome": "Pettenati S.A. Industria Textil", "tipo": "acao"},
    {"ticker": "PTNT4", "nome": "Pettenati S.A. Industria Textil", "tipo": "acao"},
    {"ticker": "QUAL3", "nome": "Qualicorp Consultoria E Corretora De Seguros S.A.", "tipo": "acao"},
    {"ticker": "QUSW3", "nome": "Quality Software S.A.", "tipo": "acao"},
    {"ticker": "RADL3", "nome": "Raia Drogasil S.A.", "tipo": "acao"},
    {"ticker": "RAIL3", "nome": "Rumo S.A.", "tipo": "acao"},
    {"ticker": "RAIZ4", "nome": "Raizen S.A.", "tipo": "acao"},
    {"ticker": "RANI3", "nome": "Irani Papel e Embalagem S.A.", "tipo": "acao"},
    {"ticker": "RANI4", "nome": "Irani Papel e Embalagem S.A.", "tipo": "acao"},
    {"ticker": "RAPT3", "nome": "Randon S.A. Implementos E Participacoes", "tipo": "acao"},
    {"ticker": "RAPT4", "nome": "Randon S.A. Implementos E Participacoes", "tipo": "acao"},
    {"ticker": "RCSL3", "nome": "Recrusul S.A.", "tipo": "acao"},
    {"ticker": "RCSL4", "nome": "Recrusul S.A.", "tipo": "acao"},
    {"ticker": "RDNI3", "nome": "Rni Negócios Imobiliários S.A.", "tipo": "acao"},
    {"ticker": "RDOR3", "nome": "Rede D Or São Luiz S.A.", "tipo": "acao"},
    {"ticker": "RECV3", "nome": "Petrorecôncavo S.A.", "tipo": "acao"},
    {"ticker": "REDE3", "nome": "Rede Energia Participações S.A.", "tipo": "acao"},
    {"ticker": "RENT3", "nome": "Localiza Rent A Car S.A.", "tipo": "acao"},
    {"ticker": "RENT4", "nome": "Localiza Rent A Car S.A.", "tipo": "acao"},
    {"ticker": "RIAA3", "nome": "Lojas Riachuelo S.A.", "tipo": "acao"},
    {"ticker": "RLOG3", "nome": "Cosan Logistica S.A.", "tipo": "acao"},
    {"ticker": "RNEW11", "nome": "Renova Energia S.A.", "tipo": "acao"},
    {"ticker": "RNEW3", "nome": "Renova Energia S.A.", "tipo": "acao"},
    {"ticker": "RNEW4", "nome": "Renova Energia S.A.", "tipo": "acao"},
    {"ticker": "ROMI3", "nome": "Industrias Romi S.A.", "tipo": "acao"},
    {"ticker": "RPAD3", "nome": "Alfa Holdings S.A.", "tipo": "acao"},
    {"ticker": "RPAD5", "nome": "Alfa Holdings S.A.", "tipo": "acao"},
    {"ticker": "RPAD6", "nome": "Alfa Holdings S.A.", "tipo": "acao"},
    {"ticker": "RPMG3", "nome": "Refinaria De Petroleos Manguinhos S.A.", "tipo": "acao"},
    {"ticker": "RSID3", "nome": "Rossi Residencial S.A.", "tipo": "acao"},
    {"ticker": "RSUL3", "nome": "Metalurgica Riosulense S.A.", "tipo": "acao"},
    {"ticker": "RSUL4", "nome": "Metalurgica Riosulense S.A.", "tipo": "acao"},
    {"ticker": "SANB11", "nome": "Bco Santander (Brasil) S.A.", "tipo": "acao"},
    {"ticker": "SANB3", "nome": "Bco Santander (Brasil) S.A.", "tipo": "acao"},
    {"ticker": "SANB4", "nome": "Bco Santander (Brasil) S.A.", "tipo": "acao"},
    {"ticker": "SAPR11", "nome": "Cia Saneamento Do Parana - Sanepar", "tipo": "acao"},
    {"ticker": "SAPR3", "nome": "Cia Saneamento Do Parana - Sanepar", "tipo": "acao"},
    {"ticker": "SAPR4", "nome": "Cia Saneamento Do Parana - Sanepar", "tipo": "acao"},
    {"ticker": "SAUD3", "nome": "Bradsaúde S.A.", "tipo": "acao"},
    {"ticker": "SBFG3", "nome": "Grupo Sbf Sa", "tipo": "acao"},
    {"ticker": "SBSP3", "nome": "Cia Saneamento Basico Est Sao Paulo", "tipo": "acao"},
    {"ticker": "SCAR3", "nome": "Sao Carlos Empreend E Participacoes S.A.", "tipo": "acao"},
    {"ticker": "SEDU3", "nome": "Somos Educação S.A.", "tipo": "acao"},
    {"ticker": "SEER3", "nome": "Ser Educacional S.A.", "tipo": "acao"},
    {"ticker": "SEQL3", "nome": "Sequoia Logistica E Transportes S.A", "tipo": "acao"},
    {"ticker": "SGPS3", "nome": "Springs Global Participacoes S.A.", "tipo": "acao"},
    {"ticker": "SHOW3", "nome": "T4F Entretenimento S.A.", "tipo": "acao"},
    {"ticker": "SHUL3", "nome": "Schulz S.A.", "tipo": "acao"},
    {"ticker": "SHUL4", "nome": "Schulz S.A.", "tipo": "acao"},
    {"ticker": "SIMH3", "nome": "Simpar S.A.", "tipo": "acao"},
    {"ticker": "SLCE3", "nome": "Slc Agricola S.A.", "tipo": "acao"},
    {"ticker": "SLED3", "nome": "Saraiva S.A. Livreiros Editores", "tipo": "acao"},
    {"ticker": "SLED4", "nome": "Saraiva S.A. Livreiros Editores", "tipo": "acao"},
    {"ticker": "SMFT3", "nome": "Smartfit Escola De Ginástica E Dança S.A.", "tipo": "acao"},
    {"ticker": "SMLS3", "nome": "Smiles Fidelidade S.A.", "tipo": "acao"},
    {"ticker": "SMTO3", "nome": "Sao Martinho S.A.", "tipo": "acao"},
    {"ticker": "SNSY3", "nome": "Sansuy S.A. Industria De Plasticos", "tipo": "acao"},
    {"ticker": "SNSY5", "nome": "Sansuy S.A. Industria De Plasticos", "tipo": "acao"},
    {"ticker": "SNSY6", "nome": "Sansuy S.A. Industria De Plasticos", "tipo": "acao"},
    {"ticker": "SOJA3", "nome": "Boa Safra Sementes S.A.", "tipo": "acao"},
    {"ticker": "SOMA3", "nome": "Grupo De Moda Soma S.A.", "tipo": "acao"},
    {"ticker": "SOND3", "nome": "Sondotecnica Engenharia Solos S.A.", "tipo": "acao"},
    {"ticker": "SOND5", "nome": "Sondotecnica Engenharia Solos S.A.", "tipo": "acao"},
    {"ticker": "SOND6", "nome": "Sondotecnica Engenharia Solos S.A.", "tipo": "acao"},
    {"ticker": "SQIA3", "nome": "Sinqia S.A.", "tipo": "acao"},
    {"ticker": "SRNA3", "nome": "Serena Energia S.A.", "tipo": "acao"},
    {"ticker": "STBP3", "nome": "Santos Brasil Participacoes S.A.", "tipo": "acao"},
    {"ticker": "STKF3", "nome": "Statkraft Energias Renovaveis S.A.", "tipo": "acao"},
    {"ticker": "STTR3", "nome": "Stara S.A. - Indústria De Implementos Agrícolas", "tipo": "acao"},
    {"ticker": "SULA11", "nome": "Sul America S.A.", "tipo": "acao"},
    {"ticker": "SULA3", "nome": "Sul America S.A.", "tipo": "acao"},
    {"ticker": "SULA4", "nome": "Sul America S.A.", "tipo": "acao"},
    {"ticker": "SUZB3", "nome": "Suzano S.A.", "tipo": "acao"},
    {"ticker": "SYNE3", "nome": "Syn Prop E Tech S.A.", "tipo": "acao"},
    {"ticker": "TAEE11", "nome": "Transmissora Aliança De Energia Elétrica S.A.", "tipo": "acao"},
    {"ticker": "TAEE3", "nome": "Transmissora Aliança De Energia Elétrica S.A.", "tipo": "acao"},
    {"ticker": "TAEE4", "nome": "Transmissora Aliança De Energia Elétrica S.A.", "tipo": "acao"},
    {"ticker": "TASA3", "nome": "Taurus Armas S.A.", "tipo": "acao"},
    {"ticker": "TASA4", "nome": "Taurus Armas S.A.", "tipo": "acao"},
    {"ticker": "TCNO3", "nome": "Tecnosolo Engenharia S.A.", "tipo": "acao"},
    {"ticker": "TCNO4", "nome": "Tecnosolo Engenharia S.A.", "tipo": "acao"},
    {"ticker": "TCSA3", "nome": "Tecnisa S.A.", "tipo": "acao"},
    {"ticker": "TECN3", "nome": "Technos S.A.", "tipo": "acao"},
    {"ticker": "TEKA3", "nome": "Teka-Tecelagem Kuehnrich S.A.", "tipo": "acao"},
    {"ticker": "TEKA4", "nome": "Teka-Tecelagem Kuehnrich S.A.", "tipo": "acao"},
    {"ticker": "TELB3", "nome": "Telec Brasileiras S.A. Telebras", "tipo": "acao"},
    {"ticker": "TELB4", "nome": "Telec Brasileiras S.A. Telebras", "tipo": "acao"},
    {"ticker": "TEND3", "nome": "Construtora Tenda S.A.", "tipo": "acao"},
    {"ticker": "TESA3", "nome": "Terra Santa Agro S.A.", "tipo": "acao"},
    {"ticker": "TFCO4", "nome": "Track & Field Co S.A.", "tipo": "acao"},
    {"ticker": "TGMA3", "nome": "Tegma Gestao Logistica S.A.", "tipo": "acao"},
    {"ticker": "TIET11", "nome": "Aes Tiete Energia Sa", "tipo": "acao"},
    {"ticker": "TIET3", "nome": "Aes Tiete Energia Sa", "tipo": "acao"},
    {"ticker": "TIET4", "nome": "Aes Tiete Energia Sa", "tipo": "acao"},
    {"ticker": "TIMS3", "nome": "Tim Participacoes S.A.", "tipo": "acao"},
    {"ticker": "TKNO3", "nome": "Tekno S.A. - Industria E Comercio", "tipo": "acao"},
    {"ticker": "TKNO4", "nome": "Tekno S.A. - Industria E Comercio", "tipo": "acao"},
    {"ticker": "TOKY3", "nome": "Grupo Toky S.A.", "tipo": "acao"},
    {"ticker": "TOTS3", "nome": "Totvs S.A.", "tipo": "acao"},
    {"ticker": "TOYB3", "nome": "Tec Toy S.A.", "tipo": "acao"},
    {"ticker": "TOYB4", "nome": "Tec Toy S.A.", "tipo": "acao"},
    {"ticker": "TPIS3", "nome": "Tpi - Triunfo Particip. E Invest. S.A.", "tipo": "acao"},
    {"ticker": "TRAD3", "nome": "Tc Traders Club S.A.", "tipo": "acao"},
    {"ticker": "TRIS3", "nome": "Trisul S.A.", "tipo": "acao"},
    {"ticker": "TTEN3", "nome": "Três Tentos Agroindustrial Sa", "tipo": "acao"},
    {"ticker": "TUPY3", "nome": "Tupy S.A.", "tipo": "acao"},
    {"ticker": "TXRX3", "nome": "Textil Renauxview S.A.", "tipo": "acao"},
    {"ticker": "TXRX4", "nome": "Textil Renauxview S.A.", "tipo": "acao"},
    {"ticker": "UCAS3", "nome": "Unicasa Indústria De Móveis S.A.", "tipo": "acao"},
    {"ticker": "UGPA3", "nome": "Ultrapar Participacoes S.A.", "tipo": "acao"},
    {"ticker": "UNIP3", "nome": "Unipar Carbocloro S.A.", "tipo": "acao"},
    {"ticker": "UNIP5", "nome": "Unipar Carbocloro S.A.", "tipo": "acao"},
    {"ticker": "UNIP6", "nome": "Unipar Carbocloro S.A.", "tipo": "acao"},
    {"ticker": "USIM3", "nome": "Usinas Sid De Minas Gerais S.A.", "tipo": "acao"},
    {"ticker": "USIM5", "nome": "Usinas Sid De Minas Gerais S.A.", "tipo": "acao"},
    {"ticker": "USIM6", "nome": "Usinas Sid De Minas Gerais S.A.", "tipo": "acao"},
    {"ticker": "VALE3", "nome": "Vale S.A.", "tipo": "acao"},
    {"ticker": "VAMO3", "nome": "Vamos Locação De Caminhões. Máquinas E Equip. S.A.", "tipo": "acao"},
    {"ticker": "VBBR3", "nome": "Vibra Energia S.A.", "tipo": "acao"},
    {"ticker": "VITT3", "nome": "Vittia Fertilizantes E Biologicos S.A.", "tipo": "acao"},
    {"ticker": "VIVA3", "nome": "Vivara Participaçoes S.A", "tipo": "acao"},
    {"ticker": "VIVR3", "nome": "Viver Incorporadora E Construtora S.A.", "tipo": "acao"},
    {"ticker": "VIVT3", "nome": "Telefônica Brasil S.A", "tipo": "acao"},
    {"ticker": "VIVT4", "nome": "Telefônica Brasil S.A", "tipo": "acao"},
    {"ticker": "VLID3", "nome": "Valid Soluções S.A.", "tipo": "acao"},
    {"ticker": "VSPT3", "nome": "Ferrovia Centro-Atlantica S.A.", "tipo": "acao"},
    {"ticker": "VSPT4", "nome": "Ferrovia Centro-Atlantica S.A.", "tipo": "acao"},
    {"ticker": "VSTE3", "nome": "Veste S.A. Estilo", "tipo": "acao"},
    {"ticker": "VTRU3", "nome": "Vitru Brasil Empreend. Particip. E Comercio S.A.", "tipo": "acao"},
    {"ticker": "VULC3", "nome": "Vulcabras/Azaleia S.A.", "tipo": "acao"},
    {"ticker": "VVEO3", "nome": "Cm Hospitalar S.A.", "tipo": "acao"},
    {"ticker": "WDCN3", "nome": "Livetech Da Bahia Industria E Comercio S.A", "tipo": "acao"},
    {"ticker": "WEGE3", "nome": "Weg S.A.", "tipo": "acao"},
    {"ticker": "WEST3", "nome": "Westwing Comercio Varejista S.A.", "tipo": "acao"},
    {"ticker": "WHRL3", "nome": "Whirlpool S.A.", "tipo": "acao"},
    {"ticker": "WHRL4", "nome": "Whirlpool S.A.", "tipo": "acao"},
    {"ticker": "WIZC3", "nome": "Wiz Co Participações E Corretagem De Seguros S.A.", "tipo": "acao"},
    {"ticker": "WLMM3", "nome": "Wlm Part. E Comércio De Máquinas E Veículos S.A.", "tipo": "acao"},
    {"ticker": "WLMM4", "nome": "Wlm Part. E Comércio De Máquinas E Veículos S.A.", "tipo": "acao"},
    {"ticker": "YDUQ3", "nome": "Estacio Participacoes S.A.", "tipo": "acao"},
    {"ticker": "ZAMP3", "nome": "Zamp S.A.", "tipo": "acao"},
]

# Lista unica para o autocomplete da navbar (ordem alfabetica por ticker)
ATIVOS = sorted(FIIS + ACOES, key=lambda a: a["ticker"])
